/* ============================================================
   SKYZONE · LOCALIZATION / LANGUAGE SYSTEM
   t(key) — merkezi çeviri fonksiyonu
   ============================================================ */
window.SKY = window.SKY || {};

SKY.LANG = (function () {
  var current = localStorage.getItem('skyzone_lang') || 'tr';

  var STRINGS = {
    // ======================== AUTH ========================
    'auth.login': { tr: 'Giriş Yap', en: 'Login' },
    'auth.register': { tr: 'Üye Ol', en: 'Register' },
    'auth.username': { tr: 'Kullanıcı adı', en: 'Username' },
    'auth.password': { tr: 'Şifre', en: 'Password' },
    'auth.password2': { tr: 'Şifre tekrar', en: 'Confirm Password' },
    'auth.email_opt': { tr: 'E-posta (opsiyonel — şifre sıfırlama için)', en: 'Email (optional — for password reset)' },
    'auth.forgot': { tr: 'Şifremi Unuttum', en: 'Forgot Password' },
    'auth.no_account': { tr: 'Hesabın yok mu?', en: "Don't have an account?" },
    'auth.has_account': { tr: 'Zaten üye misin?', en: 'Already a member?' },
    'auth.logging_in': { tr: 'Giriş yapılıyor...', en: 'Logging in...' },
    'auth.registering': { tr: 'Kayıt yapılıyor...', en: 'Registering...' },
    'auth.login_btn': { tr: 'GİRİŞ YAP', en: 'LOGIN' },
    'auth.register_btn': { tr: 'ÜYE OL', en: 'REGISTER' },
    'auth.logout': { tr: 'Çıkış Yap', en: 'Logout' },
    'auth.err_fields': { tr: 'Kullanıcı adı ve şifre gerekli', en: 'Username and password required' },
    'auth.err_fill_all': { tr: 'Tüm alanları doldur', en: 'Fill in all fields' },
    'auth.err_user_min': { tr: 'Kullanıcı adı en az 3 karakter', en: 'Username must be at least 3 characters' },
    'auth.err_user_chars': { tr: 'Kullanıcı adı sadece harf, rakam ve _ içerebilir', en: 'Username can only contain letters, numbers and _' },
    'auth.err_pass_min': { tr: 'Şifre en az 6 karakter', en: 'Password must be at least 6 characters' },
    'auth.err_pass_match': { tr: 'Şifreler eşleşmiyor', en: 'Passwords do not match' },
    'auth.err_email': { tr: 'Geçerli bir e-posta gir', en: 'Enter a valid email' },
    'auth.err_wrong': { tr: 'Kullanıcı adı veya şifre hatalı', en: 'Wrong username or password' },
    'auth.err_invalid': { tr: 'Geçersiz giriş bilgisi', en: 'Invalid login credentials' },
    'auth.err_too_many': { tr: 'Çok fazla deneme, biraz bekle', en: 'Too many attempts, wait a bit' },
    'auth.err_taken': { tr: 'Bu kullanıcı adı zaten alınmış', en: 'This username is already taken' },
    'auth.err_in_use': { tr: 'Bu kullanıcı adı zaten kayıtlı', en: 'This username is already registered' },
    'auth.err_weak': { tr: 'Şifre çok zayıf (min 6 karakter)', en: 'Password too weak (min 6 characters)' },
    'auth.err_general': { tr: 'Giriş hatası', en: 'Login error' },
    'auth.err_reg': { tr: 'Kayıt hatası', en: 'Registration error' },
    'auth.err_conn': { tr: 'Bağlantı hatası', en: 'Connection error' },
    'auth.err_not_found': { tr: 'Bu kullanıcı adı bulunamadı', en: 'Username not found' },
    'auth.success': { tr: 'Hesap oluşturuldu!', en: 'Account created!' },
    'auth.forgot_prompt': { tr: 'Şifre sıfırlama için kayıt olduğun e-posta adresini gir:', en: 'Enter the email you registered with to reset your password:' },
    'auth.forgot_sent': { tr: 'Şifre sıfırlama e-postası gönderildi!', en: 'Password reset email sent!' },
    'auth.forgot_invalid': { tr: 'Geçerli bir e-posta adresi gir', en: 'Enter a valid email address' },
    'auth.forgot_notreg': { tr: 'Bu e-posta kayıtlı değil', en: 'This email is not registered' },

    // ======================== CHARACTER ========================
    'char.create': { tr: 'Karakter Oluştur', en: 'Create Character' },
    'char.select': { tr: 'Karakter Seç', en: 'Select Character' },
    'char.name': { tr: 'Karakter adı', en: 'Character name' },
    'char.pick_city': { tr: 'ŞEHRİNİ & KAVMİNİ SEÇ', en: 'CHOOSE YOUR CITY & TRIBE' },
    'char.create_btn': { tr: 'KARAKTERİ OLUŞTUR', en: 'CREATE CHARACTER' },
    'char.new_btn': { tr: '+ Yeni Karakter Oluştur', en: '+ Create New Character' },
    'char.level': { tr: 'Seviye', en: 'Level' },
    'char.info': { tr: 'Karakter', en: 'Character' },

    // ======================== TRIBES / CITIES ========================
    'tribe.kar': { tr: 'Kar Kavmi', en: 'Ice Tribe' },
    'tribe.orman': { tr: 'Orman Kavmi', en: 'Forest Tribe' },
    'tribe.col': { tr: 'Çöl Kavmi', en: 'Desert Tribe' },
    'city.kar': { tr: 'Kar Şehri', en: 'Ice City' },
    'city.orman': { tr: 'Orman Şehri', en: 'Forest City' },
    'city.col': { tr: 'Çöl Şehri', en: 'Desert City' },

    // ======================== NAVIGATION & ZONES ========================
    'nav.back': { tr: '◂ GERİ', en: '◂ BACK' },
    'nav.capital': { tr: 'BAŞKENT', en: 'CAPITAL' },
    'nav.city_badge': { tr: 'ŞEHİR', en: 'CITY' },
    'zone.pvp_red': { tr: 'PvP Kırmızı', en: 'PvP Red' },
    'zone.pvp_blue': { tr: 'PvP Mavi', en: 'PvP Blue' },
    'zone.safe': { tr: 'Safe', en: 'Safe' },
    'zone.t1_kar': { tr: 'T1 Kar', en: 'T1 Ice' },
    'zone.t1_orman': { tr: 'T1 Orman', en: 'T1 Forest' },
    'zone.t1_col': { tr: 'T1 Çöl', en: 'T1 Desert' },
    'zone.t2_vadi': { tr: 'T2 Vadi', en: 'T2 Valley' },
    'zone.t2_bataklik': { tr: 'T2 Bataklık', en: 'T2 Swamp' },
    'zone.t2_corak': { tr: 'T2 Çorak', en: 'T2 Barren' },
    'zone.t3_merkez': { tr: 'T3 Merkez', en: 'T3 Center' },

    // ======================== MENU ========================
    'menu.character': { tr: 'Karakter', en: 'Character' },
    'menu.shop': { tr: 'Mağaza', en: 'Shop' },
    'menu.war': { tr: 'Savaş', en: 'War' },
    'menu.mail': { tr: 'Posta', en: 'Mail' },
    'menu.friends': { tr: 'Arkadaşlar', en: 'Friends' },
    'menu.alliance': { tr: 'İttifak', en: 'Alliance' },
    'menu.ranking': { tr: 'Sıralama', en: 'Ranking' },
    'menu.settings': { tr: 'Ayarlar', en: 'Settings' },
    'menu.workshop': { tr: 'Atölye', en: 'Workshop' },
    'menu.bank': { tr: 'Banka', en: 'Bank' },
    'menu.market': { tr: 'Pazaryeri', en: 'Market' },

    // ======================== CITY BUILDINGS ========================
    'bld.townhall': { tr: 'Belediye', en: 'Town Hall' },
    'bld.workshop': { tr: 'Atölye', en: 'Workshop' },
    'bld.bank': { tr: 'Banka', en: 'Bank' },
    'bld.market': { tr: 'Pazaryeri', en: 'Market' },
    'bld.treasury': { tr: 'Şehir Kasası', en: 'City Treasury' },
    'bld.gate': { tr: 'Şehir Kapısı', en: 'City Gate' },
    'bld.townhall_title': { tr: 'BELEDİYE', en: 'TOWN HALL' },
    'bld.townhall_sub': { tr: 'Politika & Yönetim', en: 'Politics & Administration' },
    'bld.townhall_desc': { tr: 'Şehir yönetimi, başkanlık seçimi ve ittifak sistemi.', en: 'City management, mayor election and alliance system.' },
    'bld.treasury_title': { tr: 'ŞEHİR KASASI', en: 'CITY TREASURY' },
    'bld.treasury_sub': { tr: 'Ortak Hazine', en: 'Shared Treasury' },
    'bld.treasury_desc': { tr: 'Vatandaş bağışlarıyla savaş itemleri ve şehir buffları craft edilir.', en: 'War items and city buffs are crafted with citizen donations.' },
    'bld.coming_soon': { tr: 'Bu sistem multiplayer aşamasında aktif olacak.', en: 'This system will be active in the multiplayer phase.' },

    // ======================== GATHERING ========================
    'gather.collect': { tr: 'TOPLA', en: 'GATHER' },
    'gather.stop': { tr: 'DUR', en: 'STOP' },
    'gather.inv_full': { tr: '🎒 Envanter dolu!', en: '🎒 Inventory full!' },
    'gather.overweight': { tr: '⚖️ Çok ağır!', en: '⚖️ Too heavy!' },
    'gather.speed': { tr: 'Toplama Hızı', en: 'Gather Speed' },
    'gather.yield': { tr: 'Yield', en: 'Yield' },
    'gather.double': { tr: '2× Şans', en: '2× Chance' },
    'gather.node_empty': { tr: 'Node tükendi!', en: 'Node depleted!' },
    'gather.no_players': { tr: 'Bölgede başka oyuncu yok', en: 'No other players in the area' },
    'gather.you': { tr: 'Sen', en: 'You' },

    // ======================== DUNGEON ========================
    'dg.title': { tr: 'DUNGEON', en: 'DUNGEON' },
    'dg.floor': { tr: 'KAT', en: 'FLOOR' },
    'dg.enter': { tr: 'Kata Gir', en: 'Enter Floor' },
    'dg.only_fields': { tr: 'Dungeon sadece bölgelerde', en: 'Dungeon only in field zones' },
    'dg.select_floor': { tr: 'Kat Seç', en: 'Select Floor' },
    'dg.active': { tr: 'Aktif', en: 'Active' },
    'dg.fighting': { tr: 'Savaşılıyor...', en: 'Fighting...' },
    'dg.boss_attack': { tr: '👹 Boss saldırısı!', en: '👹 Boss attack!' },
    'dg.boss_appeared': { tr: 'Boss belirdi!', en: 'Boss appeared!' },
    'dg.auto_on': { tr: 'Auto ON', en: 'Auto ON' },
    'dg.auto_off': { tr: 'Auto OFF', en: 'Auto OFF' },
    'dg.floor_white': { tr: 'Beyaz Kat', en: 'White Floor' },
    'dg.floor_green': { tr: 'Yeşil Kat', en: 'Green Floor' },
    'dg.floor_blue': { tr: 'Mavi Kat', en: 'Blue Floor' },
    'dg.floor_orange': { tr: 'Turuncu Kat', en: 'Orange Floor' },
    'dg.floor_red': { tr: 'Kırmızı Kat', en: 'Red Floor' },
    'dg.summary': { tr: 'Dungeon Özeti', en: 'Dungeon Summary' },
    'dg.kills': { tr: 'Öldürme', en: 'Kills' },
    'dg.boss_kills': { tr: 'Boss Öldürme', en: 'Boss Kills' },
    'dg.gold': { tr: 'Altın', en: 'Gold' },
    'dg.items': { tr: 'Eşya', en: 'Items' },
    'dg.stones': { tr: 'Taş', en: 'Stones' },
    'dg.charms': { tr: 'Tılsım', en: 'Charms' },
    'dg.died': { tr: '💀 Öldün — şehre döndün.', en: '💀 You died — returned to city.' },
    'dg.died_respawn': { tr: '💀 Öldün! 3sn sonra devam...', en: '💀 You died! Resuming in 3s...' },

    // ======================== TRAVEL ========================
    'travel.here': { tr: 'Buradasın', en: 'You are here' },
    'travel.option': { tr: 'Seyahat seçeneği', en: 'Travel option' },
    'travel.go': { tr: '▶ Seyahat Et', en: '▶ Travel' },
    'travel.at_here': { tr: '● Buradasın', en: '● You are here' },
    'travel.tier': { tr: 'Tier', en: 'Tier' },
    'travel.pvp': { tr: 'PvP', en: 'PvP' },
    'travel.distance': { tr: 'Mesafe', en: 'Distance' },
    'travel.resource': { tr: 'Ana kaynak', en: 'Main resource' },
    'travel.pvp_red': { tr: '☠ Kırmızı (T3)', en: '☠ Red (T3)' },
    'travel.pvp_blue': { tr: '⚠ Mavi (T2)', en: '⚠ Blue (T2)' },
    'travel.pvp_safe': { tr: 'Safe (Yeşil)', en: 'Safe (Green)' },
    'travel.arrived': { tr: 'Varış', en: 'Arrived' },

    // ======================== BAG / INVENTORY ========================
    'bag.title': { tr: 'Çanta', en: 'Bag' },
    'bag.all': { tr: 'Tümü', en: 'All' },
    'bag.equip': { tr: 'Ekipman', en: 'Equipment' },
    'bag.raw': { tr: 'Hammadde', en: 'Materials' },
    'bag.use': { tr: 'Tüketim', en: 'Consumables' },
    'bag.misc': { tr: 'Diğer', en: 'Other' },
    'bag.empty': { tr: 'Bu kategoride eşya yok.', en: 'No items in this category.' },
    'bag.item_count': { tr: 'eşya', en: 'items' },
    'bag.slot': { tr: 'Yuva', en: 'Slot' },
    'bag.weight': { tr: 'Ağırlık', en: 'Weight' },
    'bag.equip_btn': { tr: 'Kuşan', en: 'Equip' },
    'bag.unequip_btn': { tr: 'Çıkar', en: 'Unequip' },
    'bag.sell_btn': { tr: 'Sat', en: 'Sell' },
    'bag.sell_all': { tr: 'Hepsini Sat', en: 'Sell All' },
    'bag.drop_btn': { tr: 'At', en: 'Drop' },
    'bag.use_btn': { tr: 'Kullan', en: 'Use' },
    'bag.open_btn': { tr: '📦 Aç', en: '📦 Open' },
    'bag.deposit': { tr: '🏦', en: '🏦' },
    'bag.compare': { tr: '⚖️ Karşılaştır', en: '⚖️ Compare' },
    'bag.mount_equip': { tr: '🐎 Bineği Kuşan', en: '🐎 Equip Mount' },
    'bag.drag_hint': { tr: 'Sürükleyerek değiştir', en: 'Drag to swap' },
    'bag.workshop_hint': { tr: 'Atölye\'de kullanılır', en: 'Used in Workshop' },
    'bag.equipped': { tr: 'Kuşanıldı', en: 'Equipped' },
    'bag.unequipped': { tr: 'Çıkarıldı', en: 'Unequipped' },
    'bag.to_bank': { tr: 'Bankaya Yatır', en: 'Deposit to Bank' },
    'bag.bank_in_city': { tr: 'Bankaya yatırmak için şehirde ol.', en: 'Must be in city to deposit to bank.' },

    // ======================== EQUIPMENT LABELS ========================
    'eq.silah': { tr: 'Silah', en: 'Weapon' },
    'eq.kask': { tr: 'Kask', en: 'Helmet' },
    'eq.zirh': { tr: 'Zırh', en: 'Armor' },
    'eq.eldiven': { tr: 'Eldiven', en: 'Gloves' },
    'eq.bot': { tr: 'Bot', en: 'Boots' },
    'eq.pelerin': { tr: 'Pelerin', en: 'Cape' },
    'eq.binek': { tr: 'Binek', en: 'Mount' },
    'eq.canta': { tr: 'Çanta', en: 'Bag' },
    'eq.alet': { tr: 'Alet', en: 'Tool' },
    'eq.set': { tr: 'Set', en: 'Set' },

    // ======================== RARITY ========================
    'rar.0': { tr: 'SIRADAN', en: 'COMMON' },
    'rar.1': { tr: 'SIRADIŞI', en: 'UNCOMMON' },
    'rar.2': { tr: 'NADİR', en: 'RARE' },
    'rar.3': { tr: 'EPİK', en: 'EPIC' },
    'rar.4': { tr: 'EFSANEVİ', en: 'LEGENDARY' },

    // ======================== QUALITY ========================
    'qual.1': { tr: 'Sıradan', en: 'Common' },
    'qual.2': { tr: 'İyi', en: 'Good' },
    'qual.3': { tr: 'Nadir', en: 'Rare' },
    'qual.4': { tr: 'Epik', en: 'Epic' },
    'qual.5': { tr: 'Efsanevi', en: 'Legendary' },
    'qual.avg': { tr: 'Ortalama Kalite', en: 'Average Quality' },

    // ======================== STATS ========================
    'stat.general_cp': { tr: 'Genel CP', en: 'General CP' },
    'stat.pve_cp': { tr: 'PvE CP', en: 'PvE CP' },
    'stat.pvp_cp': { tr: 'PvP CP', en: 'PvP CP' },
    'stat.boss_cp': { tr: 'Boss CP', en: 'Boss CP' },
    'stat.crit': { tr: 'Kritik', en: 'Critical' },
    'stat.dodge': { tr: 'Dodge', en: 'Dodge' },
    'stat.cape_proc': { tr: 'Cape Proc', en: 'Cape Proc' },
    'stat.combat_time': { tr: 'Savaş Süresi', en: 'Combat Time' },
    'stat.gather_speed': { tr: 'Toplama Hızı', en: 'Gather Speed' },
    'stat.yield': { tr: 'Yield', en: 'Yield' },
    'stat.double_chance': { tr: '2× Şans', en: '2× Chance' },
    'stat.gold_bonus': { tr: 'Altın Bonus', en: 'Gold Bonus' },
    'stat.travel_speed': { tr: 'Seyahat', en: 'Travel' },
    'stat.item_drop': { tr: 'Item Drop', en: 'Item Drop' },
    'stat.stats': { tr: 'STATLAR', en: 'STATS' },
    'stat.carry': { tr: 'Taşıma', en: 'Carry' },
    'stat.speed': { tr: 'Hız', en: 'Speed' },

    // ======================== CRAFT / WORKSHOP ========================
    'craft.title': { tr: '⚒️ ATÖLYE', en: '⚒️ WORKSHOP' },
    'craft.sub': { tr: 'Craft Sistemi', en: 'Crafting System' },
    'craft.tab_craft': { tr: 'Üretim', en: 'Craft' },
    'craft.tab_enhance': { tr: 'Yükseltme', en: 'Enhancement' },
    'craft.primary': { tr: 'ANA', en: 'PRIMARY' },
    'craft.secondary': { tr: 'İKİNCİL', en: 'SECONDARY' },
    'craft.tertiary': { tr: 'ÜÇÜNCÜL', en: 'TERTIARY' },
    'craft.output': { tr: 'Çıkış', en: 'Output' },
    'craft.produce': { tr: '⚒ ÜRET', en: '⚒ CRAFT' },
    'craft.success_100': { tr: '%100 başarı', en: '100% success' },
    'craft.only_city': { tr: '🔨 Atölye sadece şehirde', en: '🔨 Workshop only in city' },

    // ======================== ENHANCEMENT ========================
    'enh.title': { tr: '🔨 Yükseltme', en: '🔨 Enhancement' },
    'enh.item_select': { tr: 'Item Seç', en: 'Select Item' },
    'enh.stone': { tr: 'Taş', en: 'Stone' },
    'enh.protection': { tr: 'Koruma', en: 'Protection' },
    'enh.current': { tr: 'Mevcut', en: 'Current' },
    'enh.enhance_btn': { tr: '⚡ YÜKSELT', en: '⚡ ENHANCE' },
    'enh.warning': { tr: 'DİKKAT!', en: 'WARNING!' },
    'enh.break_risk': { tr: 'seviyesinde kırılma riski var. Koruma tılsımı önerilir.', en: 'level has break risk. Protection charm recommended.' },
    'enh.charm_break': { tr: 'Kırılma', en: 'Break' },
    'enh.charm_drop': { tr: 'Düşüş', en: 'Drop' },
    'enh.stone_select': { tr: 'Taş Seç', en: 'Select Stone' },
    'enh.upgrade': { tr: '✨ Renk Yükselt', en: '✨ Color Upgrade' },
    'enh.transition': { tr: 'Geçiş', en: 'Transition' },
    'enh.success_rate': { tr: 'Başarı', en: 'Success' },
    'enh.fail_drops': { tr: 'e düşer', en: 'drops to' },
    'enh.cost': { tr: 'Maliyet', en: 'Cost' },
    'enh.free': { tr: 'Ücretsiz', en: 'Free' },
    'enh.no_charm': { tr: 'Tılsımsız', en: 'No Charm' },
    'enh.protect': { tr: 'Koru', en: 'Protect' },

    // ======================== BANK ========================
    'bank.title': { tr: '🏦 BANKA', en: '🏦 BANK' },
    'bank.only_city': { tr: '🏦 Banka sadece şehirde', en: '🏦 Bank only in city' },
    'bank.to_bank': { tr: '→ Bankaya At', en: '→ To Bank' },
    'bank.to_inv': { tr: '← Envantere Al', en: '← To Inventory' },
    'bank.inventory': { tr: 'Envanter', en: 'Inventory' },

    // ======================== MISC ITEMS ========================
    'misc.stone3': { tr: '+%3 Taş', en: '+3% Stone' },
    'misc.stone6': { tr: '+%6 Taş', en: '+6% Stone' },
    'misc.stone9': { tr: '+%9 Taş', en: '+9% Stone' },
    'misc.stone12': { tr: '+%12 Taş', en: '+12% Stone' },
    'misc.stone15': { tr: '+%15 Taş', en: '+15% Stone' },
    'misc.stone3_desc': { tr: 'Sıradan yükseltme taşı. +%3 enhancement verir.', en: 'Common enhancement stone. Gives +3% enhancement.' },
    'misc.stone6_desc': { tr: 'Sıradışı yükseltme taşı. +%6 enhancement verir.', en: 'Uncommon enhancement stone. Gives +6% enhancement.' },
    'misc.stone9_desc': { tr: 'Nadir yükseltme taşı. +%9 enhancement verir.', en: 'Rare enhancement stone. Gives +9% enhancement.' },
    'misc.stone12_desc': { tr: 'Epik yükseltme taşı. +%12 enhancement verir.', en: 'Epic enhancement stone. Gives +12% enhancement.' },
    'misc.stone15_desc': { tr: 'Efsanevi yükseltme taşı. +%15 enhancement verir.', en: 'Legendary enhancement stone. Gives +15% enhancement.' },
    'misc.charm_break': { tr: 'Kırılma Tılsımı', en: 'Break Protection Charm' },
    'misc.charm_break_desc': { tr: 'Enhancement sırasında item kırılmasını engeller.', en: 'Prevents item breaking during enhancement.' },
    'misc.charm_drop': { tr: 'Düşüş Tılsımı', en: 'Drop Protection Charm' },
    'misc.charm_drop_desc': { tr: 'Enhancement düşüşünü engeller.', en: 'Prevents enhancement drop.' },
    'misc.charm_color': { tr: 'Renk Tılsımı', en: 'Color Charm' },
    'misc.charm_color_desc': { tr: 'Renk yükseltme başarısızlığında düşüşü engeller.', en: 'Prevents drop on color upgrade failure.' },
    'misc.enhChest': { tr: 'Yükseltme Sandığı', en: 'Enhancement Chest' },
    'misc.enhChest_desc': { tr: 'İçinden yükseltme taşları ve koruma tılsımları çıkabilir.', en: 'May contain enhancement stones and protection charms.' },
    'misc.goldChest': { tr: 'Altın Sandığı', en: 'Gold Chest' },
    'misc.goldChest_desc': { tr: 'İçinden altın çıkar. (500-5000💰)', en: 'Contains gold. (500-5000💰)' },
    'misc.mountBox': { tr: 'Binek Kutusu', en: 'Mount Box' },
    'misc.mountBox_desc': { tr: 'İçinden binek, taş, tılsım ve altın çıkabilir. Nadir binek şansı!', en: 'May contain mounts, stones, charms and gold. Rare mount chance!' },

    // ======================== FRIENDS ========================
    'friends.title': { tr: 'Arkadaşlar', en: 'Friends' },
    'friends.list': { tr: 'Arkadaşlar', en: 'Friends' },
    'friends.requests': { tr: 'İstekler', en: 'Requests' },
    'friends.online': { tr: 'Çevrimiçi', en: 'Online' },
    'friends.offline': { tr: 'Çevrimdışı', en: 'Offline' },
    'friends.send_msg': { tr: 'Mesaj', en: 'Message' },
    'friends.remove': { tr: 'Çıkar', en: 'Remove' },
    'friends.accept': { tr: 'Kabul', en: 'Accept' },
    'friends.reject': { tr: 'Reddet', en: 'Reject' },
    'friends.no_friends': { tr: 'Henüz arkadaşın yok', en: 'No friends yet' },
    'friends.no_requests': { tr: 'Bekleyen istek yok', en: 'No pending requests' },
    'friends.req_sent': { tr: 'Arkadaşlık isteği gönderildi!', en: 'Friend request sent!' },
    'friends.req_accepted': { tr: 'Arkadaşlık kabul edildi!', en: 'Friend request accepted!' },

    // ======================== PVP ========================
    'pvp.attack': { tr: '⚔️ Saldır', en: '⚔️ Attack' },
    'pvp.fighting': { tr: 'Savaşılıyor...', en: 'Fighting...' },
    'pvp.won': { tr: 'Kazandın!', en: 'You won!' },
    'pvp.lost': { tr: 'Kaybettin!', en: 'You lost!' },

    // ======================== CHAT ========================
    'chat.placeholder': { tr: 'Mesaj yaz...', en: 'Type a message...' },
    'chat.global': { tr: 'Dünya', en: 'World' },
    'chat.city': { tr: 'Şehir', en: 'City' },
    'chat.private': { tr: 'Özel', en: 'Private' },

    // ======================== RANKING ========================
    'rank.title': { tr: '🏆 Sıralama', en: '🏆 Ranking' },
    'rank.loading': { tr: 'Yükleniyor...', en: 'Loading...' },
    'rank.error': { tr: 'Sıralama yüklenemedi', en: 'Failed to load ranking' },

    // ======================== SETTINGS ========================
    'settings.title': { tr: '⚙️ Ayarlar', en: '⚙️ Settings' },
    'settings.language': { tr: 'Dil', en: 'Language' },
    'settings.turkish': { tr: 'Türkçe', en: 'Türkçe' },
    'settings.english': { tr: 'English', en: 'English' },
    'settings.sound': { tr: 'Ses', en: 'Sound' },
    'settings.on': { tr: 'Açık', en: 'On' },
    'settings.off': { tr: 'Kapalı', en: 'Off' },
    'settings.save': { tr: 'Kaydet', en: 'Save' },

    // ======================== SHOP ========================
    'shop.title': { tr: '💎 Mağaza', en: '💎 Shop' },
    'shop.premium': { tr: 'Premium Üyelik', en: 'Premium Membership' },
    'shop.buy': { tr: 'Satın Al', en: 'Buy' },
    'shop.inv_slot': { tr: 'Envanter Slotu', en: 'Inventory Slot' },
    'shop.bank_slot': { tr: 'Banka Slotu', en: 'Bank Slot' },
    'shop.market_slot': { tr: 'Market Slotu', en: 'Market Slot' },

    // ======================== WAR / EVENT ========================
    'war.title': { tr: 'Kavim Savaşı', en: 'Tribe War' },
    'war.join': { tr: '⚔️ SAVAŞA KATIL', en: '⚔️ JOIN WAR' },
    'war.city_walls': { tr: 'Şehir Surları', en: 'City Walls' },
    'war.harvest_charm': { tr: 'Bereket Tılsımı', en: 'Harvest Charm' },
    'war.hammer_statue': { tr: 'Çekiç Heykeli', en: 'Hammer Statue' },
    'war.star_podium': { tr: 'Yıldız Kürsüsü', en: 'Star Podium' },
    'war.merchant_seal': { tr: 'Tüccar Mührü', en: 'Merchant Seal' },

    // ======================== STONES (Kadim Taş) ========================
    'stone.kar_castle': { tr: 'Kar Kalesi Taşı', en: 'Ice Castle Stone' },
    'stone.orman_castle': { tr: 'Orman Kalesi Taşı', en: 'Forest Castle Stone' },
    'stone.col_castle': { tr: 'Çöl Kalesi Taşı', en: 'Desert Castle Stone' },
    'stone.kar_field': { tr: 'Kar Ovası Taşı', en: 'Ice Plains Stone' },
    'stone.orman_field': { tr: 'Orman Çayırı Taşı', en: 'Forest Meadow Stone' },
    'stone.col_field': { tr: 'Çöl Vahası Taşı', en: 'Desert Oasis Stone' },
    'stone.kar_t2': { tr: 'Kar Vadisi Taşı', en: 'Ice Valley Stone' },
    'stone.orman_t2': { tr: 'Orman Koridoru Taşı', en: 'Forest Corridor Stone' },
    'stone.col_t2': { tr: 'Çöl Çorak Taşı', en: 'Desert Barren Stone' },
    'stone.golden': { tr: 'Altın Kadim Taş', en: 'Golden Ancient Stone' },

    // ======================== PERK LABELS ========================
    'perk.cp': { tr: 'CP', en: 'CP' },
    'perk.yield': { tr: 'toplama yield', en: 'gather yield' },
    'perk.yieldp': { tr: 'yield', en: 'yield' },
    'perk.gatherspeed': { tr: 'toplama hızı', en: 'gather speed' },
    'perk.double': { tr: '2× toplama', en: '2× gather' },
    'perk.itemdrop': { tr: 'item drop', en: 'item drop' },
    'perk.gold': { tr: 'altın kazancı', en: 'gold income' },
    'perk.craftdrop': { tr: 'craft drop', en: 'craft drop' },
    'perk.bossloot': { tr: 'boss loot', en: 'boss loot' },
    'perk.exp': { tr: 'item exp', en: 'item exp' },
    'perk.vsmob': { tr: 'CP vs mob', en: 'CP vs mob' },
    'perk.vspvp': { tr: 'CP vs PvP', en: 'CP vs PvP' },
    'perk.vsboss': { tr: 'CP vs boss', en: 'CP vs boss' },
    'perk.vswar': { tr: 'CP savaşta', en: 'CP in war' },
    'perk.combattime': { tr: 'savaş süresi ↓', en: 'combat time ↓' },
    'perk.travel': { tr: 'seyahat hızı', en: 'travel speed' },
    'perk.loadpenalty': { tr: 'yük cezası ↓', en: 'load penalty ↓' },
    'perk.weight': { tr: 'ağırlık limiti', en: 'weight limit' },
    'perk.invslot': { tr: 'envanter slot', en: 'inventory slot' },
    'perk.capeproc': { tr: 'cape proc şansı', en: 'cape proc chance' },
    'perk.capemult': { tr: 'cape çarpanı', en: 'cape multiplier' },
    'perk.crit': { tr: 'kritik', en: 'critical' },
    'perk.dodge': { tr: 'dodge', en: 'dodge' },
    'perk.taxcut': { tr: 'market vergi ↓', en: 'market tax ↓' },
    'perk.lossreduce': { tr: 'item kaybı ↓', en: 'item loss ↓' },
    'perk.crosstier': { tr: 'cross-tier verim', en: 'cross-tier efficiency' },
    'perk.rareup': { tr: 'nadirlik şansı', en: 'rarity chance' },
    'perk.tierup': { tr: 'tier-up şansı', en: 'tier-up chance' },
    'perk.zoneyield': { tr: 'zone yield', en: 'zone yield' },

    // ======================== COMMON ========================
    'common.close': { tr: 'Kapat', en: 'Close' },
    'common.confirm': { tr: 'Onayla', en: 'Confirm' },
    'common.cancel': { tr: 'İptal', en: 'Cancel' },
    'common.yes': { tr: 'Evet', en: 'Yes' },
    'common.no': { tr: 'Hayır', en: 'No' },
    'common.ok': { tr: 'Tamam', en: 'OK' },
    'common.loading': { tr: 'Yükleniyor...', en: 'Loading...' },
    'common.error': { tr: 'Hata', en: 'Error' },
    'common.piece': { tr: 'adet', en: 'pcs' },
    'common.family': { tr: 'Aile', en: 'Family' },
    'common.tier_color': { tr: 'Tier / Renk', en: 'Tier / Color' },
    'common.amount': { tr: 'Adet', en: 'Amount' },
    'common.no_perk': { tr: 'Perk yok', en: 'No perks' },
    'common.starter': { tr: 'Başlangıç ekipmanı (T0)', en: 'Starter equipment (T0)' },
    'common.food': { tr: 'Yemek', en: 'Food' },
    'common.potion': { tr: 'İksir', en: 'Potion' },
    'common.food_30m': { tr: 'Yemek (30 dk)', en: 'Food (30 min)' },
    'common.potion_3m': { tr: 'İksir (3 dk)', en: 'Potion (3 min)' },
    'common.session_kicked': { tr: 'Başka bir cihazdan giriş yapıldı.', en: 'Logged in from another device.' },
    'common.session_limit': { tr: 'Aynı hesaba aynı anda sadece 1 cihazdan giriş yapılabilir.', en: 'Only 1 device can be logged into the same account at a time.' },
    'common.relogin': { tr: 'Tekrar Giriş Yap', en: 'Login Again' },
    'common.compare': { tr: 'Karşılaştır', en: 'Compare' },
    'common.inventory': { tr: 'Envanter', en: 'Inventory' },
    'common.equipped_label': { tr: 'Kuşanılmış', en: 'Equipped' },
    'common.equal': { tr: 'Eşit', en: 'Equal' },

    // ======================== MOUNT ========================
    'mount.speed': { tr: 'Hız', en: 'Speed' },
    'mount.carry': { tr: 'Taşıma', en: 'Carry' },
    'mount.red_stat': { tr: 'KIRMIZI STAT', en: 'RED STAT' },

    // ======================== RESOURCE FAMILIES ========================
    'family.cevher': { tr: 'Cevher', en: 'Ore' },
    'family.deri': { tr: 'Deri', en: 'Leather' },
    'family.odun': { tr: 'Odun', en: 'Wood' },
    'family.tas': { tr: 'Taş', en: 'Stone' },
    'family.bitki': { tr: 'Bitki', en: 'Herb' },
    'family.balik': { tr: 'Balık', en: 'Fish' },

    // ======================== CHARACTER (extra) ========================
    'char.play': { tr: 'Oyna', en: 'Play' },
    'char.err_name': { tr: 'Karakter adı gir', en: 'Enter character name' },
    'char.err_name_min': { tr: 'Karakter adı en az 2 karakter', en: 'Character name must be at least 2 characters' },
    'char.err_city': { tr: 'Bir şehir seç!', en: 'Pick a city!' },
    'char.err_max': { tr: 'Maksimum 3 karakter', en: 'Maximum 3 characters' },
    'char.err_nodata': { tr: 'Karakter verisi bulunamadı', en: 'Character data not found' },
    'char.err_conn_retry': { tr: 'Bağlantı hatası — tekrar dene', en: 'Connection error — try again' },
    'char.offline_mode': { tr: '⚠️ Çevrimdışı mod — veri eski olabilir', en: '⚠️ Offline mode — data may be outdated' },
    'char.delete_confirm': { tr: 'Bu karakter silinecek. Emin misin?', en: 'This character will be deleted. Are you sure?' },

    // ======================== AUTH (extra) ========================
    'auth.connecting': { tr: 'Bağlanıyor...', en: 'Connecting...' },
    'auth.err_session': { tr: 'Oturum hatası', en: 'Session error' },

    // ======================== TUTORIAL ========================
    'tutorial.welcome': { tr: 'Hoş Geldin', en: 'Welcome' },
    'tutorial.map': { tr: 'Harita', en: 'Map' },
    'tutorial.map_desc': { tr: "Node'a dokun, topla", en: 'Tap a node, gather' },
    'tutorial.workshop': { tr: 'Menü → Atölye', en: 'Menu → Workshop' },
    'tutorial.workshop_desc': { tr: 'Ekipman üret', en: 'Craft equipment' },
    'tutorial.bag': { tr: 'Çanta', en: 'Bag' },
    'tutorial.bag_desc': { tr: 'Giy, CP artır', en: 'Equip, raise CP' },
    'tutorial.dungeon': { tr: 'Dungeon', en: 'Dungeon' },
    'tutorial.dungeon_desc': { tr: 'Mob/boss, loot', en: 'Mob/boss, loot' },
    'tutorial.menu': { tr: 'Menü', en: 'Menu' },
    'tutorial.menu_desc': { tr: 'Banka, Pazar', en: 'Bank, Market' },
    'tutorial.start_info': { tr: 'Başlangıç: 2.000 altın, T0 set, T1 alet. Haritadaki bir node\'a dokun!', en: 'Start: 2,000 gold, T0 set, T1 tool. Tap a node on the map!' },
    'tutorial.start_btn': { tr: 'Başla', en: 'Start' },

    // ======================== IDLE / BACKGROUND ========================
    'idle.gathered': { tr: 'Arka plan: {count} item toplandı ({time}sn)', en: 'Background: {count} items gathered ({time}s)' },
    'idle.dungeon': { tr: 'Arka plan: {kills} mob kesildi, +{gold}💰 ({time}sn)', en: 'Background: {kills} mobs killed, +{gold}💰 ({time}s)' },

    // ======================== BAG (extra) ========================
    'bag.deposited': { tr: 'Yatırıldı', en: 'Deposited' },
    'bag.dropped': { tr: 'Atıldı', en: 'Dropped' },

    // ======================== BANK (extra) ========================
    'bank.withdrawn': { tr: 'Çekildi', en: 'Withdrawn' },

    // ======================== ENHANCEMENT (extra) ========================
    'enh.failed': { tr: 'Başarısız', en: 'Failed' },
    'enh.break_prevented': { tr: 'Kırılma engellendi', en: 'Break prevented' },
    'enh.drop_prevented': { tr: 'Düşüş engellendi', en: 'Drop prevented' },
    'enh.item_broken': { tr: 'İTEM KIRILDI!', en: 'ITEM BROKEN!' },
    'enh.success_label': { tr: 'Başarılı!', en: 'Success!' },
    'enh.dropped': { tr: 'Düştü', en: 'Dropped' },
    'enh.color_protected': { tr: 'Renk korundu', en: 'Color protected' },
    'enh.no_items': { tr: 'Yükseltilebilir ekipman yok', en: 'No upgradeable equipment' },
    'enh.no_stones': { tr: 'Enhancement taşın yok', en: 'No enhancement stones' },
    'enh.no_charms': { tr: 'Tılsımın yok. Dungeon\'dan düşer.', en: 'No charms. Drops from dungeon.' },
    'enh.charm_select': { tr: 'Koruma Seç', en: 'Select Protection' },
    'enh.charm_optional': { tr: 'Opsiyonel tılsım', en: 'Optional charm' },
    'enh.charm_break_desc': { tr: 'Kırılma engellenir → sadece -%3', en: 'Break prevented → only -3%' },
    'enh.charm_drop_desc': { tr: 'Düşüş engellenir → sadece başarısız', en: 'Drop prevented → only fail' },
    'enh.no_charm_desc': { tr: 'Tılsım kullanma', en: 'No charm used' },

    // ======================== CRAFT (extra) ========================
    'craft.produced': { tr: 'Üretildi', en: 'Crafted' },

    // ======================== SHOP (extra) ========================
    'shop.no_gold': { tr: 'Yetersiz altın', en: 'Not enough gold' },
    'shop.change_city': { tr: 'Şehir Değiştir', en: 'Change City' },
    'shop.bank_slot_ok': { tr: 'Banka yuvası açıldı! (+60 slot)', en: 'Bank slot opened! (+60 slot)' },
    'shop.inv_slot_ok': { tr: 'Envanter yuvası açıldı! (+24 slot)', en: 'Inventory slot opened! (+24 slot)' },
    'shop.exp_boost': { tr: 'Tüm item EXP +1000', en: 'All item EXP +1000' },
    'shop.city_changed': { tr: 'Yeni vatandaşlık', en: 'New citizenship' },

    // ======================== PVP (extra) ========================
    'pvp.own_tribe': { tr: 'Kendi kavmine saldıramazsın!', en: "Can't attack your own tribe!" },
    'pvp.fight_start': { tr: '{name} ile savaş! {time}sn...', en: 'Fighting {name}! {time}s...' },
    'pvp.defeated': { tr: 'Yenildi', en: 'Defeated' },

    // ======================== WAR (extra) ========================
    'war.not_active': { tr: 'Savaş aktif değil', en: 'War not active' },
    'war.captured': { tr: 'ele geçirildi', en: 'captured' },
    'war.damage': { tr: 'hasar', en: 'damage' },
    'war.healed': { tr: 'iyileştirme', en: 'healing' },

    // ======================== FRIENDS (extra) ========================
    'friends.sent_req': { tr: 'Arkadaşlık isteği gönderdi', en: 'Sent friend request' },
    'friends.rejected': { tr: 'Reddedildi', en: 'Rejected' },
    'friends.removed': { tr: 'Arkadaş silindi', en: 'Friend removed' },
    'friends.remove_confirm': { tr: 'Bu arkadaşı silmek istediğine emin misin?', en: 'Are you sure you want to remove this friend?' },

    // ======================== CHAT (extra) ========================
    'chat.no_system': { tr: 'Sistem kanalına mesaj gönderilemez', en: "Can't send messages to system channel" },
    'chat.no_messages': { tr: 'Henüz mesaj yok...', en: 'No messages yet...' },
    'chat.tribe': { tr: 'Kavim', en: 'Tribe' },
    'chat.system': { tr: 'Sistem', en: 'System' },
    'chat.pm_to': { tr: '{name} adlı oyuncuya mesaj...', en: 'Message to {name}...' },
    'chat.pm_started': { tr: '{name} ile özel sohbet', en: 'Private chat with {name}' },

    // ======================== MARKET (extra) ========================
    'market.invalid_price': { tr: 'Geçersiz fiyat', en: 'Invalid price' },
    'market.listed': { tr: 'Listelendi!', en: 'Listed!' },
    'market.cancelled': { tr: 'Listeleme iptal edildi', en: 'Listing cancelled' },
    'market.sold': { tr: 'satıldı', en: 'sold' },
    'market.sold_mail': { tr: '{buyer} senin {item} ürününü {price} altına satın aldı!', en: '{buyer} bought your {item} for {price} gold!' },
    'market.buyer1': { tr: 'Gezgin Ali', en: 'Traveler Ali' },
    'market.buyer2': { tr: 'Tüccar Zeynep', en: 'Merchant Zeynep' },
    'market.buyer3': { tr: 'Demirci Kemal', en: 'Smith Kemal' },
    'market.buyer4': { tr: 'Avcı Elif', en: 'Hunter Elif' },
    'market.buyer5': { tr: 'Usta Bora', en: 'Master Bora' },

    // ======================== CHARINFO ========================
    'charinfo.tribe': { tr: 'Kavim', en: 'Tribe' },
    'charinfo.city': { tr: 'Şehir', en: 'City' },
    'charinfo.active': { tr: 'Aktif', en: 'Active' },
    'charinfo.none': { tr: 'Yok', en: 'None' },
    'charinfo.days': { tr: 'gün', en: 'days' },
    'charinfo.total_cp': { tr: 'Toplam CP', en: 'Total CP' },
    'charinfo.gathered': { tr: 'Toplanan', en: 'Gathered' },
    'charinfo.deaths': { tr: 'Ölüm', en: 'Deaths' },

    // ======================== MOUNT (extra) ========================
    'mount.not_found': { tr: 'Binek bulunamadı', en: 'Mount not found' },
    'mount.unequipped': { tr: 'Binek çıkarıldı', en: 'Mount unequipped' },
    'mount.added': { tr: 'envantere eklendi', en: 'added to inventory' },
    'mount.open_from_bag': { tr: 'Binek kutusunu çantadan aç', en: 'Open mount box from bag' },

    // ======================== RANKING (extra) ========================
    'rank.empty': { tr: 'Henüz sıralama verisi yok', en: 'No ranking data yet' },

    // ======================== COMMON (extra) ========================
    'common.saved': { tr: 'Kaydedildi', en: 'Saved' },

    // ======================== ZONE NAMES (full IDs) ========================
    'zone.city_kar': { tr: 'Kar Şehri', en: 'Ice City' },
    'zone.city_orman': { tr: 'Orman Şehri', en: 'Forest City' },
    'zone.city_col': { tr: 'Çöl Şehri', en: 'Desert City' },
    'zone.t1_kar': { tr: 'Kar Ovası', en: 'Ice Plains' },
    'zone.t1_orman': { tr: 'Orman Çayırı', en: 'Forest Meadow' },
    'zone.t1_col': { tr: 'Çöl Vahası', en: 'Desert Oasis' },
    'zone.t2_kar': { tr: 'Kar Vadisi', en: 'Ice Valley' },
    'zone.t2_orman': { tr: 'Orman Koridoru', en: 'Forest Corridor' },
    'zone.t2_col': { tr: 'Çöl Çorak', en: 'Desert Barren' },
    'zone.t3_merkez': { tr: 'T3 Merkez', en: 'T3 Center' },

    // ======================== GATHER / PLAYERS ========================
    'gather.stop': { tr: 'DUR', en: 'STOP' },
    'gather.start': { tr: 'TOPLA', en: 'GATHER' },
    'gather.no_players': { tr: 'Bölgede başka oyuncu yok', en: 'No other players in area' },
    'gather.you': { tr: 'Sen', en: 'You' },
    'gather.player': { tr: 'Oyuncu', en: 'Player' },

    // ======================== DUNGEON ========================
    'dg.only_fields': { tr: 'Dungeon sadece bölgelerde', en: 'Dungeons only in field zones' },
    'dg.floor_select': { tr: 'Kat Seç', en: 'Select Floor' },
    'dg.floor': { tr: 'KAT', en: 'FLOOR' },
    'dg.enter_floor': { tr: 'Kata Gir', en: 'Enter Floor' },
    'dg.kill': { tr: 'kill', en: 'kill' },

    // ======================== TRAVEL ========================
    'travel.here': { tr: 'Buradasın', en: 'You are here' },
    'travel.option': { tr: 'Seyahat seçeneği', en: 'Travel option' },
    'travel.pvp_red': { tr: '☠ Kırmızı (T3)', en: '☠ Red (T3)' },
    'travel.pvp_blue': { tr: '⚠ Mavi (T2)', en: '⚠ Blue (T2)' },
    'travel.pvp_safe': { tr: 'Safe (Yeşil)', en: 'Safe (Green)' },
    'travel.tier': { tr: 'Tier:', en: 'Tier:' },
    'travel.pvp': { tr: 'PvP:', en: 'PvP:' },
    'travel.distance': { tr: 'Mesafe:', en: 'Distance:' },
    'travel.resource': { tr: 'Ana kaynak:', en: 'Main resource:' },
    'travel.capital': { tr: 'Başkent', en: 'Capital' },
    'travel.here_btn': { tr: '● Buradasın', en: '● You are here' },
    'travel.go': { tr: '▶ Seyahat Et', en: '▶ Travel' },
    'travel.sec': { tr: 'sn', en: 's' },
    'travel.city_res': { tr: 'Banka · Market · Atölye', en: 'Bank · Market · Workshop' },
    'travel.here_upper': { tr: 'BURADASIN', en: 'HERE' },

    // ======================== ITEM INFO ========================
    'item.carry': { tr: 'Taşıma', en: 'Carry' },
    'item.speed': { tr: 'Hız', en: 'Speed' },
    'item.gather_speed': { tr: 'Toplama Hızı', en: 'Gather Speed' },
    'item.enhancement': { tr: 'Enhancement', en: 'Enhancement' },
    'item.perks': { tr: 'Perkler', en: 'Perks' },
    'item.empty_slot': { tr: 'Boş slot', en: 'Empty slot' },
    'item.not_found': { tr: 'Item bulunamadı', en: 'Item not found' },
    'item.ordinary': { tr: 'Sıradan', en: 'Common' },
    'item.pcs': { tr: 'adet', en: 'pcs' },
    'item.mount': { tr: 'Binek', en: 'Mount' },

    // ======================== BAG EXTRA ========================
    'bag.use_btn': { tr: 'Kullan', en: 'Use' },
    'bag.sell_mat': { tr: 'Sat', en: 'Sell' },
    'bag.open_mountbox': { tr: '🎁 Aç', en: '🎁 Open' },
    'bag.sell_one': { tr: 'Sat (1)', en: 'Sell (1)' },
    'bag.sell_all': { tr: 'Hepsini Sat', en: 'Sell All' },
    'bag.used_in_workshop': { tr: "Atölye'de kullanılır", en: 'Used in Workshop' },
    'bag.inventory': { tr: 'Envanter', en: 'Inventory' },
    'bag.equal': { tr: '= Eşit', en: '= Equal' },
    'bag.equip_action': { tr: 'Kuşan', en: 'Equip' },
    'bag.compare_title': { tr: '⚖️ Karşılaştır', en: '⚖️ Compare' },
    'bag.slot_label': { tr: 'Yuva', en: 'Slot' },
    'bag.items': { tr: 'eşya', en: 'items' },

    // ======================== CONSUMABLE ========================
    'cons.food': { tr: 'Yemek (30 dk)', en: 'Food (30 min)' },
    'cons.potion': { tr: 'İksir (3 dk)', en: 'Potion (3 min)' },

    // ======================== MAT INFO ========================
    'mat.family': { tr: 'Aile', en: 'Family' },
    'mat.tier_color': { tr: 'Tier / Renk', en: 'Tier / Color' },
    'mat.count': { tr: 'Adet', en: 'Count' },
    'mat.deposit': { tr: '🏦 Bankaya Yatır', en: '🏦 Deposit to Bank' },
    'mat.deposit_hint': { tr: 'Bankaya yatırmak için şehirde ol.', en: 'Be in city to deposit to bank.' },
    'mat.family_suffix': { tr: 'ailesi', en: 'family' },
    'mat.craft_mat': { tr: 'craft malzemesi', en: 'craft material' },

    // ======================== WORKSHOP / CRAFT ========================
    'craft.title': { tr: '⚒️ ATÖLYE', en: '⚒️ WORKSHOP' },
    'craft.subtitle': { tr: 'Craft Sistemi', en: 'Craft System' },
    'craft.tab_craft': { tr: 'Üretim', en: 'Craft' },
    'craft.tab_enh': { tr: 'Yükseltme', en: 'Enhance' },
    'craft.output': { tr: 'Çıkış →', en: 'Output →' },
    'craft.do': { tr: '⚒ ÜRET', en: '⚒ CRAFT' },
    'craft.success': { tr: '%100 başarı', en: '100% success' },
    'craft.primary': { tr: 'ANA', en: 'PRIMARY' },
    'craft.secondary': { tr: 'İKİNCİL', en: 'SECONDARY' },
    'craft.tertiary': { tr: 'ÜÇÜNCÜL', en: 'TERTIARY' },
    'craft.buff_item': { tr: 'Buff item', en: 'Buff item' },

    // ======================== ENHANCE ========================
    'enh.title': { tr: '🔨 Yükseltme', en: '🔨 Enhance' },
    'enh.current': { tr: 'Mevcut', en: 'Current' },
    'enh.stone_select': { tr: 'Taş Seç', en: 'Select Stone' },
    'enh.total': { tr: 'toplam', en: 'total' },
    'enh.charm_label': { tr: 'Tılsım:', en: 'Charm:' },
    'enh.charm_none': { tr: 'Yok', en: 'None' },
    'enh.break_risk': { tr: 'kırılma riski!', en: 'break risk!' },
    'enh.do': { tr: '⚡ YÜKSELT', en: '⚡ ENHANCE' },
    'enh.no_item': { tr: 'Yükseltilecek item yok.', en: 'No items to enhance.' },
    'enh.item_select': { tr: 'Item Seç', en: 'Select Item' },
    'enh.stone': { tr: 'Taş', en: 'Stone' },
    'enh.protection': { tr: 'Koruma', en: 'Protection' },
    'enh.equipment': { tr: 'Ekipman', en: 'Equipment' },
    'enh.warning': { tr: 'DİKKAT!', en: 'WARNING!' },
    'enh.break_warn': { tr: 'seviyesinde <strong>kırılma riski</strong> var. Koruma tılsımı önerilir.', en: 'level has <strong>break risk</strong>. Protection charm recommended.' },
    'enh.charm_break': { tr: '🔴 Kırılma', en: '🔴 Break' },
    'enh.charm_drop': { tr: '🟡 Düşüş', en: '🟡 Drop' },

    // ======================== UPGRADE (COLOR) ========================
    'up.title': { tr: '✨ Renk Yükselt', en: '✨ Color Upgrade' },
    'up.transition': { tr: 'Geçiş', en: 'Transition' },
    'up.success_rate': { tr: 'Başarı', en: 'Success' },
    'up.fail': { tr: "'e düşer", en: ' on fail' },
    'up.cost': { tr: 'Maliyet', en: 'Cost' },
    'up.free': { tr: 'Ücretsiz', en: 'Free' },
    'up.no_charm': { tr: 'Tılsımsız', en: 'No charm' },
    'up.protect': { tr: '🟢 Koru', en: '🟢 Protect' },
    'up.do': { tr: 'Yükselt', en: 'Upgrade' },
    'up.color_charm': { tr: '🟢 Renk Düşüş Tılsımı', en: '🟢 Color Drop Charm' },
    'up.color_hint': { tr: 'Renk yükselt.', en: 'Upgrade color.' },

    // ======================== BANK ========================
    'bank.only_city': { tr: '🏦 Banka sadece şehirde', en: '🏦 Bank only in city' },
    'bank.city_lock': { tr: '🔒 Sadece kendi şehrinin ({city}) bankasına erişebilirsin', en: "🔒 You can only access your city's ({city}) bank" },
    'bank.upgrade_ok': { tr: '✅ +25 slot · −5.000💰', en: '✅ +25 slots · -5,000💰' },
    'bank.no_slot': { tr: 'Hedefte boş slot yok!', en: 'No empty slots in destination!' },
    'bank.stack_full': { tr: 'Hedef stack dolu', en: 'Destination stack full' },
    'bank.transferred': { tr: 'aktarıldı', en: 'transferred' },
    'bank.all': { tr: 'Tümü', en: 'All' },
    'bank.available': { tr: 'adet mevcut', en: 'available' },
    'bank.inv_to_bank': { tr: 'ENVANTER <span class="arrow">→</span> BANKA', en: 'INVENTORY <span class="arrow">→</span> BANK' },
    'bank.bank_to_inv': { tr: 'BANKA <span class="arrow">→</span> ENVANTER', en: 'BANK <span class="arrow">→</span> INVENTORY' },

    // ======================== MARKET ========================
    'mkt.only_city': { tr: '🏪 Pazar sadece şehirde', en: '🏪 Market only in city' },
    'mkt.all': { tr: 'Tümü', en: 'All' },
    'mkt.weapon': { tr: '⚔️ Silah', en: '⚔️ Weapon' },
    'mkt.helmet': { tr: '🪖 Kask', en: '🪖 Helmet' },
    'mkt.armor': { tr: '🥋 Zırh', en: '🥋 Armor' },
    'mkt.cape': { tr: '🦋 Pelerin', en: '🦋 Cape' },
    'mkt.gloves': { tr: '🧤 Eldiven', en: '🧤 Gloves' },
    'mkt.boots': { tr: '👢 Bot', en: '👢 Boots' },
    'mkt.mount_cat': { tr: '🐎 Binek', en: '🐎 Mount' },
    'mkt.bag_cat': { tr: '🎒 Çanta', en: '🎒 Bag' },
    'mkt.tool_cat': { tr: '⛏️ Alet', en: '⛏️ Tool' },
    'mkt.set_cat': { tr: '🦺 Set', en: '🦺 Set' },
    'mkt.rawmat': { tr: '📦 Hammadde', en: '📦 Raw Material' },
    'mkt.white': { tr: 'Beyaz', en: 'White' },
    'mkt.green': { tr: 'Yeşil', en: 'Green' },
    'mkt.blue': { tr: 'Mavi', en: 'Blue' },
    'mkt.orange': { tr: 'Turuncu', en: 'Orange' },
    'mkt.red': { tr: 'Kırmızı', en: 'Red' },
    'mkt.search': { tr: '🔍 Ara...', en: '🔍 Search...' },
    'mkt.buy_tab': { tr: 'Satın Al', en: 'Buy' },
    'mkt.sell_tab': { tr: 'Satışa Koy', en: 'Sell' },
    'mkt.orders_tab': { tr: 'Siparişlerim', en: 'My Orders' },
    'mkt.no_results': { tr: 'Sonuç bulunamadı.', en: 'No results found.' },
    'mkt.buy_btn': { tr: 'Satın Al', en: 'Buy' },
    'mkt.sell_hint': { tr: 'Listele → satıldığında %{tax} vergi kesilir. NPC alıcılar 1-60 dk içinde satın alır.', en: 'List → {tax}% tax on sale. NPC buyers purchase within 1-60 min.' },
    'mkt.list_btn': { tr: 'Listele', en: 'List' },
    'mkt.no_items': { tr: 'Satılacak eşya yok.', en: 'No items to sell.' },
    'mkt.no_orders': { tr: 'Aktif listeleme yok.', en: 'No active listings.' },
    'mkt.orders_hint': { tr: 'Satışa koyduğun eşyalar burada görünür.', en: 'Your listed items appear here.' },
    'mkt.listed_ago': { tr: 'dk önce listelendi', en: 'min ago' },
    'mkt.cancel': { tr: 'İptal', en: 'Cancel' },
    'mkt.seller': { tr: 'Satıcı', en: 'Seller' },
    'mkt.rawmat_label': { tr: 'Hammadde', en: 'Raw material' },
    'mkt.remaining': { tr: 'kaldı', en: 'remaining' },
    'mkt.quantity': { tr: 'Miktar:', en: 'Quantity:' },
    'mkt.total': { tr: 'Toplam', en: 'Total' },
    'mkt.insufficient_gold': { tr: '❌ Yetersiz altın ({amount} gerekli)', en: '❌ Insufficient gold ({amount} needed)' },
    'mkt.inv_full': { tr: '❌ Envanter dolu', en: '❌ Inventory full' },
    'mkt.bought': { tr: 'satın alındı', en: 'bought' },
    'mkt.min': { tr: 'dk', en: 'min' },
    'mkt.hr': { tr: 'sa', en: 'hr' },

    // ======================== MOUNT ========================
    'mount.no_mount': { tr: 'Kuşanılı binek yok.', en: 'No mount equipped.' },
    'mount.types': { tr: 'Binek Türleri', en: 'Mount Types' },
    'mount.box_title': { tr: 'Binek Kutusu', en: 'Mount Box' },
    'mount.box_open': { tr: 'Çantandan 🎁 Binek Kutusu itemini aç.', en: 'Open 🎁 Mount Box item from your bag.' },
    'mount.box_none': { tr: 'Binek kutusu yok.', en: 'No mount boxes.' },
    'mount.drop_hint': { tr: 'Mob %0.03 · Boss K1-K5 artan şansla düşer', en: 'Mob 0.03% · Boss F1-F5 increasing chance' },
    'mount.unequip': { tr: 'Bırakarak Çıkar', en: 'Unequip' },
    'mount.speed': { tr: 'Hız', en: 'Speed' },
    'mount.weight': { tr: 'Ağırlık', en: 'Weight' },
    'mount.special': { tr: 'Özel', en: 'Special' },
    'mount.star': { tr: 'Yıldız', en: 'Star' },
    'mount.red_stat': { tr: 'KIRMIZI STAT', en: 'RED STAT' },
    'mount.rk_0': { tr: 'Sıradan', en: 'Common' },
    'mount.rk_1': { tr: 'Sıradışı', en: 'Uncommon' },
    'mount.rk_2': { tr: 'Nadir', en: 'Rare' },
    'mount.rk_3': { tr: 'Epik', en: 'Epic' },
    'mount.rk_4': { tr: 'Efsanevi', en: 'Legendary' },

    // ======================== SHOP ========================
    'shop.premium': { tr: 'Premium', en: 'Premium' },
    'shop.slots': { tr: 'Slot', en: 'Slots' },
    'shop.crystals': { tr: 'Kristal', en: 'Crystals' },
    'shop.gem_balance': { tr: 'Kristal Bakiye', en: 'Crystal Balance' },
    'shop.premium_title': { tr: 'PREMIUM ÜYELİK', en: 'PREMIUM MEMBERSHIP' },
    'shop.active': { tr: 'AKTİF', en: 'ACTIVE' },
    'shop.days_left': { tr: 'gün kaldı', en: 'days left' },
    'shop.offline_earn': { tr: 'Offline kazanç', en: 'Offline earnings' },
    'shop.inv_slot': { tr: 'Envanter', en: 'Inventory' },
    'shop.bank_slot': { tr: 'Banka', en: 'Bank' },
    'shop.drop_rate': { tr: 'Drop oranı', en: 'Drop rate' },
    'shop.market_tax': { tr: 'Market vergisi', en: 'Market tax' },
    'shop.xp_bonus': { tr: 'XP bonusu', en: 'XP bonus' },
    'shop.gold_name': { tr: 'Altın isim', en: 'Gold name' },
    'shop.day_30': { tr: '30 Gün', en: '30 Days' },
    'shop.starter_pack': { tr: 'BAŞLANGIÇ PAKETİ (Tek Seferlik)', en: 'STARTER PACK (One Time)' },
    'shop.starter_desc': { tr: '30 gün Premium + 200 Kristal + 3 Envanter Slotu', en: '30 days Premium + 200 Crystals + 3 Inventory Slots' },
    'shop.inv_type': { tr: 'Envanter', en: 'Inventory' },
    'shop.bank_type': { tr: 'Banka', en: 'Bank' },
    'shop.market_type': { tr: 'Market', en: 'Market' },
    'shop.crystal_label': { tr: 'kristal', en: 'crystals' },

    // ======================== WAR ========================
    'war.loading': { tr: 'Savaş sistemi yükleniyor...', en: 'War system loading...' },

    // ======================== NPC SELLERS ========================
    'npc.seller1': { tr: 'Tüccar Ahmet', en: 'Merchant Ahmet' },
    'npc.seller2': { tr: 'Usta Zeynep', en: 'Master Zeynep' },
    'npc.seller3': { tr: 'Gezgin Ali', en: 'Traveler Ali' },
    'npc.seller4': { tr: 'Demirci Kemal', en: 'Smith Kemal' },
    'npc.seller5': { tr: 'Avcı Elif', en: 'Hunter Elif' },

    // ======================== WAR EXTRA ========================
    'war.active': { tr: 'SAVAŞ AKTİF', en: 'WAR ACTIVE' },
    'war.peace': { tr: 'BARIŞ ZAMANI', en: 'PEACE TIME' },
    'war.next': { tr: 'Sonraki', en: 'Next' },
    'war.stones_label': { tr: 'Taşlar', en: 'Stones' },
    'war.stone_count': { tr: 'Taş', en: 'Stone' },
    'war.owner': { tr: 'Sahip', en: 'Owner' },
    'war.empty': { tr: 'Boş', en: 'Empty' },
    'war.cooldown': { tr: 'Soğuma...', en: 'Cooldown...' },
    'war.log': { tr: 'Savaş Logu', en: 'War Log' },

    // ======================== TRADE ========================
    'trade.specialty': { tr: 'Uzmanlık', en: 'Specialty' },
    'trade.gold_want': { tr: 'Altın istiyor', en: 'Wants gold' },
    'trade.your_offer': { tr: 'Senin Teklif', en: 'Your Offer' },
    'trade.offer': { tr: 'Teklifi', en: 'Offer' },
    'trade.gold': { tr: 'Altın:', en: 'Gold:' },
    'trade.confirm': { tr: 'Onayla', en: 'Confirm' },
    'trade.confirmed': { tr: 'ONAYLANDI ✓', en: 'CONFIRMED ✓' },
    'trade.npc_waiting': { tr: 'NPC bekliyor...', en: 'NPC waiting...' },
    'trade.slots_full': { tr: 'Takas slotları dolu', en: 'Trade slots full' },
    'trade.no_equip': { tr: 'Envanterde ekipman yok', en: 'No equipment in inventory' },
    'trade.select_item': { tr: '🤝 Item Seç', en: '🤝 Select Item' },
    'trade.for_trade': { tr: 'Takas için', en: 'For trade' },
    'trade.select_equip': { tr: 'Ekipman Seç', en: 'Select Equipment' },
    'trade.insufficient': { tr: 'Yetersiz altın', en: 'Insufficient gold' },
    'trade.offer_sth': { tr: 'Bir şeyler teklif et', en: 'Offer something' },
    'trade.complete': { tr: '✅ Takas tamamlandı!', en: '✅ Trade completed!' },

    // ======================== BUFF INFO ========================
    'buff.premium_title': { tr: '★ Premium ({days} gün)', en: '★ Premium ({days} days)' },
    'buff.premium_src': { tr: 'Satın alınmış premium abonelik', en: 'Purchased premium subscription' },
    'buff.premium_val': { tr: '+1 Env. Yuvası · +1 Banka Yuvası · +%10 Drop · +%15 XP · -%25 Vergi · +%30 Offline', en: '+1 Inv. Slot · +1 Bank Slot · +10% Drop · +15% XP · -25% Tax · +30% Offline' },
    'buff.city_src': { tr: 'Şehir kasasından', en: 'From city treasury' },
    'buff.city_val': { tr: 'Şehir buffı (haftalık)', en: 'City buff (weekly)' },
    'buff.cons_src': { tr: 'Tüketim itemi (yemek/iksir)', en: 'Consumable item (food/potion)' },
    'buff.remaining': { tr: 'kaldı', en: 'remaining' },
    'buff.expired': { tr: 'Süresi dolmuş', en: 'Expired' },

    // ======================== LISTING ========================
    'list.set_price': { tr: 'Fiyat Belirle', en: 'Set Price' },
    'list.npc_hint': { tr: 'NPC alıcılar 1-60 dk içinde satın alabilir', en: 'NPC buyers may purchase within 1-60 min' },
    'list.quantity': { tr: 'Miktar', en: 'Quantity' },
    'list.unit_price': { tr: 'Birim Fiyat', en: 'Unit Price' },
    'list.suggested': { tr: 'Önerilen', en: 'Suggested' },
    'list.total': { tr: 'Toplam', en: 'Total' },
    'list.tax': { tr: 'Vergi', en: 'Tax' },
    'list.net': { tr: 'Net', en: 'Net' },
    'list.sell_title': { tr: '🏪 Satışa Koy', en: '🏪 List for Sale' },

    // ======================== MAILBOX ========================
    'mail.pending_gold': { tr: 'Bekleyen altın', en: 'Pending gold' },
    'mail.collect_all': { tr: 'Tümünü Al', en: 'Collect All' },
    'mail.empty': { tr: 'Posta kutun boş.', en: 'Your mailbox is empty.' },
    'mail.collect': { tr: 'Al', en: 'Collect' },
    'mail.collected': { tr: 'Alındı ✓', en: 'Collected ✓' },

    // ======================== RANKING ========================
    'rank.title': { tr: 'Sıralama', en: 'Ranking' },
    'rank.player_label': { tr: 'Oyuncular', en: 'Players' },

    // ======================== SETTINGS ========================
    'settings.title': { tr: 'Ayarlar', en: 'Settings' },
    'settings.lang': { tr: 'Dil', en: 'Language' },

    'craft.only_city': { tr: '🔨 Atölye sadece şehirde', en: '🔨 Workshop only in city' },

    // ======================== STONE MODAL ========================
    'stone.not_loaded': { tr: 'Savaş sistemi yüklenmedi', en: 'War system not loaded' },
    'stone.not_found': { tr: 'Taş bulunamadı', en: 'Stone not found' },
    'stone.golden': { tr: '✦ Altın Kadim Taş', en: '✦ Golden Ancient Stone' },
    'stone.regional': { tr: 'Bölge Taşı', en: 'Regional Stone' },
    'stone.owner_label': { tr: 'Sahip', en: 'Owner' },
    'stone.no_owner': { tr: 'Sahipsiz', en: 'Unclaimed' },
    'stone.war_desc': { tr: 'Taşları ele geçirerek şehrine buff kazan. Taşın sahibi savunma, diğerleri saldırı yapabilir.', en: 'Capture stones to earn buffs for your city. The owner defends while others attack.' },
    'stone.next_war': { tr: 'Sonraki savaş', en: 'Next war' },
    'stone.players': { tr: 'Oyuncular', en: 'Players' },
    'stone.defense': { tr: '🛡️ SAVUNMA', en: '🛡️ DEFENSE' },
    'stone.attack': { tr: '⚔️ SALDIRI', en: '⚔️ ATTACK' },
    'stone.you': { tr: 'Sen', en: 'You' },
    'stone.join_defense': { tr: '🛡️ Savunmaya Katıl', en: '🛡️ Join Defense' },
    'stone.join_attack': { tr: '⚔️ Saldırıya Katıl', en: '⚔️ Join Attack' },
    'stone.war_inactive': { tr: 'Savaş aktif değil — sonraki savaşı bekle', en: 'War not active — wait for next war' },
    'stone.war_title': { tr: '⚔️ Kadim Taş Savaşı', en: '⚔️ Ancient Stone War' },

    // ======================== NPC WAR NAMES ========================
    'npc.def1': { tr: 'Kaleci Yusuf', en: 'Keeper Yusuf' },
    'npc.def2': { tr: 'Nöbetçi Kemal', en: 'Guard Kemal' },
    'npc.def3': { tr: 'Koruyucu Ada', en: 'Protector Ada' },
    'npc.atk1': { tr: 'Savaşçı Ozan', en: 'Warrior Ozan' },
    'npc.atk2': { tr: 'Akıncı Burak', en: 'Raider Burak' },
    'npc.atk3': { tr: 'Fatih Deniz', en: 'Conqueror Deniz' },

    // ======================== MISC REMAINING ========================
    'mail.read': { tr: 'Postalar okundu', en: 'Mails read' },
    'stat.gathered': { tr: 'Toplanan', en: 'Gathered' },
    'stat.deaths': { tr: 'Ölüm', en: 'Deaths' },
    'pvp.attack_started': { tr: 'saldırısı başlatıldı (PvP)', en: 'attack started (PvP)' },
    'pvp.trade_sent': { tr: 'ile takas teklifi gönderildi', en: 'trade request sent' },
    'city.kar_full': { tr: '❄️ Kar Şehri', en: '❄️ Ice City' },
    'city.orman_full': { tr: '🌲 Orman Şehri', en: '🌲 Forest City' },
    'city.col_full': { tr: '🏜️ Çöl Şehri', en: '🏜️ Desert City' },
    'dg.active': { tr: 'Aktif', en: 'Active' },
    'dg.floor_prefix': { tr: 'K', en: 'F' },

    // ======================== UNEQUIP / ACTIONS ========================
    'action.unequip': { tr: 'Çıkar', en: 'Unequip' },
    'action.equip_btn': { tr: 'Giy', en: 'Equip' },

    // ======================== DATA — Materials ========================
    'mat.cevher_1': { tr: 'Ham Cevher', en: 'Raw Ore' },
    'mat.cevher_2': { tr: 'Saf Cevher', en: 'Pure Ore' },
    'mat.cevher_3': { tr: 'Mithril Cevheri', en: 'Mithril Ore' },
    'mat.deri_1': { tr: 'Ham Deri', en: 'Raw Hide' },
    'mat.deri_2': { tr: 'Kalın Deri', en: 'Thick Hide' },
    'mat.deri_3': { tr: 'Ejder Derisi', en: 'Dragon Hide' },
    'mat.odun_1': { tr: 'Ham Odun', en: 'Raw Wood' },
    'mat.odun_2': { tr: 'Sert Odun', en: 'Hard Wood' },
    'mat.odun_3': { tr: 'Kadim Odun', en: 'Ancient Wood' },
    'mat.tas_1': { tr: 'Ham Taş', en: 'Raw Stone' },
    'mat.tas_2': { tr: 'Saf Kristal', en: 'Pure Crystal' },
    'mat.tas_3': { tr: 'Yakut Taşı', en: 'Ruby Stone' },
    'mat.bitki_1': { tr: 'Ham Ot', en: 'Raw Herb' },
    'mat.bitki_2': { tr: 'Nadir Bitki', en: 'Rare Plant' },
    'mat.bitki_3': { tr: 'Kadim Çiçek', en: 'Ancient Flower' },
    'mat.balik_1': { tr: 'Ham Balık', en: 'Raw Fish' },
    'mat.balik_2': { tr: 'Tatlısu Balığı', en: 'Freshwater Fish' },
    'mat.balik_3': { tr: 'Altın Balık', en: 'Gold Fish' },

    // ======================== DATA — Family Labels ========================
    'fam.cevher': { tr: 'Cevher', en: 'Ore' },
    'fam.deri': { tr: 'Deri', en: 'Hide' },
    'fam.odun': { tr: 'Odun', en: 'Wood' },
    'fam.tas': { tr: 'Taş', en: 'Stone' },
    'fam.bitki': { tr: 'Bitki', en: 'Herb' },
    'fam.balik': { tr: 'Balık', en: 'Fish' },

    // ======================== DATA — Rarity ========================
    'rar.W': { tr: 'Beyaz', en: 'White' },
    'rar.G': { tr: 'Yeşil', en: 'Green' },
    'rar.B': { tr: 'Mavi', en: 'Blue' },
    'rar.O': { tr: 'Turuncu', en: 'Orange' },
    'rar.R': { tr: 'Kırmızı', en: 'Red' },

    // ======================== DATA — Node Sizes ========================
    'node.small': { tr: 'Küçük', en: 'Small' },
    'node.medium': { tr: 'Orta', en: 'Medium' },
    'node.large': { tr: 'Büyük', en: 'Large' },

    // ======================== DATA — Recipes ========================
    'recipe.kask': { tr: 'Kask', en: 'Helmet' },
    'recipe.zirh': { tr: 'Zırh', en: 'Armor' },
    'recipe.eldiven': { tr: 'Eldiven', en: 'Gloves' },
    'recipe.bot': { tr: 'Bot', en: 'Boots' },
    'recipe.pelerin': { tr: 'Pelerin', en: 'Cape' },
    'recipe.binek': { tr: 'Binek', en: 'Mount' },
    'recipe.silah': { tr: 'Silah', en: 'Weapon' },
    'recipe.alet': { tr: 'Toplama Aleti', en: 'Gathering Tool' },
    'recipe.set': { tr: 'Toplama Seti', en: 'Gathering Set' },
    'recipe.canta': { tr: 'Çanta', en: 'Bag' },
    'recipe.yemek': { tr: 'Yemek', en: 'Food' },
    'recipe.iksir': { tr: 'İksir', en: 'Potion' },

    // ======================== DATA — Perks ========================
    'perk.maden_sezgi': { tr: 'Madenci Sezgisi', en: 'Miner\'s Intuition' },
    'perk.cevik_el': { tr: 'Çevik El', en: 'Swift Hand' },
    'perk.sansli_el': { tr: 'Şanslı El', en: 'Lucky Hand' },
    'perk.yagmaci': { tr: 'Yağmacı', en: 'Plunderer' },
    'perk.tuccar': { tr: 'Tüccar', en: 'Merchant' },
    'perk.kasif': { tr: 'Kaşif', en: 'Explorer' },
    'perk.boss_avci': { tr: 'Boss Avcısı', en: 'Boss Hunter' },
    'perk.bilge': { tr: 'Bilge', en: 'Wise' },
    'perk.keskinlik': { tr: 'Keskinlik', en: 'Sharpness' },
    'perk.cellat': { tr: 'Cellat', en: 'Executioner' },
    'perk.duellocu': { tr: 'Düellocu', en: 'Duelist' },
    'perk.avci': { tr: 'Avcı', en: 'Hunter' },
    'perk.orman_usta': { tr: 'Orman Ustası', en: 'Forest Master' },
    'perk.kar_usta': { tr: 'Kar Ustası', en: 'Ice Master' },
    'perk.col_usta': { tr: 'Çöl Ustası', en: 'Desert Master' },
    'perk.savas_yorgun': { tr: 'Savaş Yorgunluğu', en: 'Battle Fatigue' },
    'perk.kalin_kafa': { tr: 'Kalın Kafa', en: 'Thick Head' },
    'perk.mob_sav': { tr: 'Mob Savunması', en: 'Mob Defense' },
    'perk.pvp_sav': { tr: 'PvP Savunması', en: 'PvP Defense' },
    'perk.boss_sav': { tr: 'Boss Savunması', en: 'Boss Defense' },
    'perk.tema_usta': { tr: '3 Tema Ustası', en: '3 Theme Master' },
    'perk.sansli_pelerin': { tr: 'Şanslı Pelerin', en: 'Lucky Cape' },
    'perk.devlet_pelerin': { tr: 'Devlet Pelerini', en: 'Royal Cape' },
    'perk.cevik_vurus': { tr: 'Çevik Vuruş', en: 'Swift Strike' },
    'perk.cevik_kacis': { tr: 'Çevik Kaçış', en: 'Swift Escape' },
    'perk.pvp_ustad': { tr: 'PvP Üstadı', en: 'PvP Master' },
    'perk.savas_tanri': { tr: 'Savaş Tanrısı', en: 'God of War' },
    'perk.sert_zirh': { tr: 'Sert Zırh', en: 'Hard Armor' },
    'perk.dayaniklilik': { tr: 'Dayanıklılık', en: 'Durability' },
    'perk.siki_kavrama': { tr: 'Sıkı Kavrama', en: 'Firm Grip' },
    'perk.kalin_eldiven': { tr: 'Kalın Eldiven', en: 'Thick Gloves' },
    'perk.hassas_denge': { tr: 'Hassas Denge', en: 'Precise Balance' },
    'perk.mob_hass': { tr: 'Mob Hassasiyeti', en: 'Mob Sensitivity' },
    'perk.duellocu_e': { tr: 'Düellocu Eldiveni', en: 'Duelist Gloves' },
    'perk.avci_e': { tr: 'Avcı Eldiveni', en: 'Hunter Gloves' },
    'perk.saglam_bot': { tr: 'Sağlam Bot', en: 'Sturdy Boots' },
    'perk.hizli_adim': { tr: 'Hızlı Adım', en: 'Fast Step' },
    'perk.cevik_ayak': { tr: 'Çevik Ayak', en: 'Swift Foot' },
    'perk.guclu_bacak': { tr: 'Güçlü Bacak', en: 'Strong Leg' },
    'perk.kalin_deri_m': { tr: 'Kalın Deri', en: 'Thick Hide' },
    'perk.yuk_kap': { tr: 'Yük Kapasitesi', en: 'Load Capacity' },
    'perk.eyer_bolme': { tr: 'Eyer Bölmesi', en: 'Saddle Slot' },
    'perk.hizli_kosu': { tr: 'Hızlı Koşu', en: 'Fast Run' },
    'perk.mob_tepki': { tr: 'Mob Tepkisi', en: 'Mob Reaction' },
    'perk.duello_binek': { tr: 'Düello Bineği', en: 'Duel Mount' },
    'perk.avci_binek': { tr: 'Avcı Bineği', en: 'Hunter Mount' },
    'perk.tema_binek': { tr: '3 Tema Bineği', en: '3 Theme Mount' },
    'perk.genis_canta': { tr: 'Geniş Çanta', en: 'Wide Bag' },
    'perk.cok_cepli': { tr: 'Çok Cebli', en: 'Multi-Pocket' },
    'perk.hafif_yapim': { tr: 'Hafif Yapım', en: 'Lightweight Build' },
    'perk.siki_baglama': { tr: 'Sıkı Bağlama', en: 'Firm Bind' },
    'perk.gezgin_canta': { tr: 'Gezgin Çantası', en: 'Traveler Bag' },
    'perk.tuccar_canta': { tr: 'Tüccar Çantası', en: 'Merchant Bag' },
    'perk.sansli_kese': { tr: 'Şanslı Kese', en: 'Lucky Purse' },
    'perk.saglam_yapim': { tr: 'Sağlam Yapım', en: 'Sturdy Build' },
    'perk.nadir_bulgu': { tr: 'Nadir Bulgu', en: 'Rare Find' },
    'perk.yonetici': { tr: '3 Yöneticisi', en: '3 Manager' },
    'perk.bereket_usta': { tr: 'Bereket Ustası', en: 'Harvest Master' },
    'perk.sansli_yumruk': { tr: 'Şanslı Yumruk', en: 'Lucky Fist' },
    'perk.bereket3': { tr: '3 Bereketi', en: '3 Harvest' },
    'perk.sezgisellik': { tr: 'Sezgisellik', en: 'Intuition' },

    // ======================== DATA — Cities ========================
    'city.kar': { tr: 'Kar Şehri', en: 'Ice City' },
    'city.orman': { tr: 'Orman Şehri', en: 'Forest City' },
    'city.col': { tr: 'Çöl Şehri', en: 'Desert City' },
    'city.kar_theme': { tr: 'Soğuk, dağlık, donmuş göller', en: 'Cold, mountainous, frozen lakes' },
    'city.orman_theme': { tr: 'Yeşil, ağaç, nehirler', en: 'Green, trees, rivers' },
    'city.col_theme': { tr: 'Kum, kaya, sıcak', en: 'Sand, rocks, hot' },

    // ======================== DATA — Zone Names ========================
    'zone.city_kar': { tr: 'Kar Şehri', en: 'Ice City' },
    'zone.city_orman': { tr: 'Orman Şehri', en: 'Forest City' },
    'zone.city_col': { tr: 'Çöl Şehri', en: 'Desert City' },
    'zone.t1_kar': { tr: 'T1 Kar Ovası', en: 'T1 Ice Plains' },
    'zone.t1_orman': { tr: 'T1 Orman Çayırı', en: 'T1 Forest Meadow' },
    'zone.t1_col': { tr: 'T1 Çöl Vahası', en: 'T1 Desert Oasis' },
    'zone.t2_kar': { tr: 'T2 Kar Koridoru', en: 'T2 Ice Corridor' },
    'zone.t2_orman': { tr: 'T2 Orman Koridoru', en: 'T2 Forest Corridor' },
    'zone.t2_col': { tr: 'T2 Çöl Koridoru', en: 'T2 Desert Corridor' },
    'zone.t3_merkez': { tr: 'T3 Kadim Merkez', en: 'T3 Ancient Center' },

    // ======================== DATA — Chests ========================
    'chest.enhChest': { tr: 'Yükseltme Sandığı', en: 'Enhancement Chest' },
    'chest.enhChest_desc': { tr: 'İçinden yükseltme taşları ve tılsımlar çıkabilir.', en: 'May contain enhancement stones and charms.' },
    'chest.goldChest': { tr: 'Altın Sandığı', en: 'Gold Chest' },
    'chest.goldChest_desc': { tr: 'İçinden altın çıkar.', en: 'Contains gold.' },

    // ======================== DATA — Buffs ========================
    'buff.gatherspeed': { tr: 'Hızlandırma', en: 'Speed Boost' },
    'buff.yield': { tr: 'Bereket', en: 'Abundance' },
    'buff.double': { tr: 'Şanslı Toplama', en: 'Lucky Gather' },
    'buff.gold': { tr: 'Altın Bonusu', en: 'Gold Bonus' },
    'buff.craftdrop': { tr: 'Crafting Drop', en: 'Crafting Drop' },
    'buff.cp': { tr: 'CP Boost', en: 'CP Boost' },
    'buff.combattime': { tr: 'Savaş Süresi', en: 'Battle Duration' },
    'buff.itemdrop': { tr: 'Item Drop', en: 'Item Drop' },
    'buff.bossloot': { tr: 'Boss Loot', en: 'Boss Loot' },

    // ======================== DATA — Mount Types ========================
    'mount.at': { tr: 'Savaş Atı', en: 'War Horse' },
    'mount.kurt': { tr: 'Dire Kurt', en: 'Dire Wolf' },
    'mount.fil': { tr: 'Savaş Fili', en: 'War Elephant' },
    'mount.inv_slot': { tr: '+1 Envanter Slotu', en: '+1 Inventory Slot' },

    // ======================== DATA — Shop ========================
    'shop.inv_slot_1': { tr: '+1 Envanter Slotu', en: '+1 Inventory Slot' },
    'shop.inv_slot_3': { tr: '+3 Envanter Slotu', en: '+3 Inventory Slots' },
    'shop.bank_slot_1': { tr: '+1 Banka Slotu', en: '+1 Bank Slot' },
    'shop.bank_slot_5': { tr: '+5 Banka Slotu', en: '+5 Bank Slots' },
    'shop.mkt_slot_1': { tr: '+1 Market Slotu', en: '+1 Market Slot' },
    'shop.crystal_100': { tr: '100 Kristal', en: '100 Crystals' },
    'shop.crystal_300': { tr: '300 Kristal', en: '300 Crystals' },
    'shop.crystal_600': { tr: '600 Kristal', en: '600 Crystals' },
    'shop.crystal_1200': { tr: '1200 Kristal', en: '1200 Crystals' },

    // ======================== DATA — Trade NPC ========================
    'trade.npc_ahmet': { tr: 'Tüccar Ahmet', en: 'Merchant Ahmet' },
    'trade.npc_zeynep': { tr: 'Usta Zeynep', en: 'Master Zeynep' },
    'trade.npc_ali': { tr: 'Gezgin Ali', en: 'Traveler Ali' },
    'trade.npc_kemal': { tr: 'Demirci Kemal', en: 'Smith Kemal' },
    'trade.npc_elif': { tr: 'Avcı Elif', en: 'Hunter Elif' },

    // ======================== DATA — War Stones ========================
    'ws.kar_city': { tr: 'Kar Kalesi Taşı', en: 'Ice Castle Stone' },
    'ws.kar_t1': { tr: 'Kar Ovası Taşı', en: 'Ice Plains Stone' },
    'ws.kar_t2': { tr: 'Kar Vadisi Taşı', en: 'Ice Valley Stone' },
    'ws.orman_city': { tr: 'Orman Kalesi Taşı', en: 'Forest Castle Stone' },
    'ws.orman_t1': { tr: 'Orman Çayırı Taşı', en: 'Forest Meadow Stone' },
    'ws.orman_t2': { tr: 'Orman Koridoru Taşı', en: 'Forest Corridor Stone' },
    'ws.col_city': { tr: 'Çöl Kalesi Taşı', en: 'Desert Castle Stone' },
    'ws.col_t1': { tr: 'Çöl Vahası Taşı', en: 'Desert Oasis Stone' },
    'ws.col_t2': { tr: 'Çöl Koridoru Taşı', en: 'Desert Corridor Stone' },
    'ws.golden': { tr: 'Altın Kadim Taş', en: 'Golden Ancient Stone' },

    // ======================== CRAFT.JS Messages ========================
    'craft.insufficient_family': { tr: 'yetersiz', en: 'insufficient' },
    'craft.insufficient_mat': { tr: 'Yetersiz malzeme', en: 'Insufficient materials' },
    'craft.inv_full': { tr: 'Envanter dolu (malzeme harcandı değil)', en: 'Inventory full (materials not consumed)' },
    'craft.t0_no_enh': { tr: 'T0 item geliştirilemez', en: 'T0 item cannot be enhanced' },
    'craft.max_enh': { tr: 'Max +%90', en: 'Max +90%' },
    'craft.no_stone': { tr: 'taşın yok', en: 'you have no stone' },
    'craft.t0_no_up': { tr: 'T0 yükseltilemez', en: 'T0 cannot be upgraded' },
    'craft.already_red': { tr: 'Zaten Kırmızı', en: 'Already Red' },
    'craft.max_listings': { tr: 'Maksimum 3 listeleme hakkın var', en: 'Maximum 3 listings allowed' },
    'craft.invalid_price': { tr: 'Geçersiz fiyat', en: 'Invalid price' },
    'craft.insufficient_mat_short': { tr: 'Yetersiz malzeme', en: 'Insufficient materials' },
    'craft.item_not_found': { tr: 'Item bulunamadı', en: 'Item not found' },
    'craft.insufficient_gold': { tr: 'Yetersiz altın', en: 'Insufficient gold' },
    'craft.max_bank': { tr: 'Max 4 yuva', en: 'Max 4 slots' },
    'craft.already_bought': { tr: 'Zaten alınmış', en: 'Already purchased' },
    'craft.item_missing': { tr: 'Item yok', en: 'Item not found' },

    // ======================== CHAT.JS ========================
    'chat.kavim': { tr: 'kavim', en: 'tribe' },
    'chat.dunya': { tr: 'dünya', en: 'world' },
    'chat.ozel': { tr: 'özel', en: 'private' },
    'chat.sistem': { tr: 'sistem', en: 'system' },
    'chat.system': { tr: 'Sistem', en: 'System' },
    'chat.welcome': { tr: 'Oyuna hoş geldin, {name}!', en: 'Welcome to the game, {name}!' },
    'chat.city_info': { tr: 'Şehrin: {city}. Kavim kanalında şehir arkadaşlarınla konuş.', en: 'Your city: {city}. Talk to your city friends in the tribe channel.' },
    'chat.select_friend': { tr: 'Arkadaşlar menüsünden bir oyuncu seç.', en: 'Select a player from the friends menu.' },

    // ======================== EVENTS.JS ========================
    'evt.tribe_kar': { tr: 'Kar', en: 'Ice' },
    'evt.tribe_orman': { tr: 'Orman', en: 'Forest' },
    'evt.tribe_col': { tr: 'Çöl', en: 'Desert' },
    'evt.fight_start': { tr: 'ile savaş başladı!', en: 'battle started!' },
    'evt.enemy_defeated': { tr: 'yenildi! (+1 Kill)', en: 'defeated! (+1 Kill)' },
    'evt.player_died': { tr: 'tarafından yenildin!', en: 'defeated you!' },
    'evt.wait_sec': { tr: 'sn bekleme...', en: 'sec wait...' },
    'evt.respawn': { tr: '🔄 Yeniden doğdun! Savaşmaya hazırsın.', en: '🔄 You respawned! Ready to fight.' },
    'evt.tribe_won': { tr: 'Kavmin kazandı! Kavim Savaşı Sandığı ödülü alındı!', en: 'Your tribe won! Tribal War Chest reward received!' },
    'evt.tribe_won_toast': { tr: '🏆 Kavim Savaşı Kazandınız! Ödül envantere eklendi.', en: '🏆 Tribal War Won! Reward added to inventory.' },
    'evt.tribe_lost': { tr: 'Kavmin kaybetti.', en: 'Your tribe lost.' },
    'evt.tribe_lost_suffix': { tr: 'kazandı.', en: 'won.' },
    'evt.tribe_lost_toast': { tr: '💔 Kavim Savaşı kaybedildi.', en: '💔 Tribal War lost.' },
    'evt.not_active': { tr: 'Kavim Savaşı aktif değil. Her saat başı başlar.', en: 'Tribal War not active. Starts every hour.' },
    'evt.expired': { tr: 'Kavim Savaşı süresi doldu!', en: 'Tribal War time expired!' },
    'evt.joined': { tr: '⚔️ Kavim Savaşına katıldın! Düşmanlarına saldır!', en: '⚔️ Joined Tribal War! Attack your enemies!' },
    'evt.fight_label': { tr: 'Savaş', en: 'Battle' },
    'evt.sec': { tr: 'sn', en: 'sec' },
    'evt.defeated': { tr: 'Yenildin!', en: 'Defeated!' },
    'evt.respawn_label': { tr: 'Doğma', en: 'Respawn' },
    'evt.in_combat': { tr: '⚔️ Savaşta', en: '⚔️ In Combat' },
    'evt.attack_btn': { tr: 'SALDIR', en: 'ATTACK' },

    // ======================== ENGINE.JS ========================
    'eng.cape_proc': { tr: 'Pelerin proc!', en: 'Cape proc!' },
    'eng.critical': { tr: 'Kritik!', en: 'Critical!' },
    'eng.dodge': { tr: 'Dodge! Kaçtın.', en: 'Dodge! Escaped.' },
    'eng.speed_label': { tr: 'Hız', en: 'Speed' },
    'eng.carry_label': { tr: 'Taşıma', en: 'Carry' },
    'eng.map_speed': { tr: 'harita hızı', en: 'map speed' },
    'eng.inv_slot_label': { tr: '+1 Envanter Slotu', en: '+1 Inventory Slot' },
    'eng.inv_slot_desc': { tr: 'Sabit +1 envanter yuvası', en: 'Fixed +1 inventory slot' },
    'eng.red_stat_name': { tr: 'Kırmızı Stat', en: 'Red Stat' },
    'eng.red_stat_desc': { tr: '🔴 +%5 CP — Ultra Nadir', en: '🔴 +5% CP — Ultra Rare' },

    // ======================== DUNGEON.JS ========================
    'dg.chest_enh': { tr: 'Yükseltme Sandığı', en: 'Enhancement Chest' },
    'dg.chest_gold': { tr: 'Altın Sandığı', en: 'Gold Chest' },

    // ======================== STATE.JS ========================
    'state.item_not_found': { tr: 'Item bulunamadı', en: 'Item not found' },
    'state.insufficient_exp': { tr: 'Yetersiz', en: 'Insufficient' },
    'state.exp_required': { tr: 'gerekli', en: 'required' },

    // ======================== CHAT BOT NAMES ========================
    'chatbot.kavim_1': { tr: 'Kılıçusta', en: 'Swordmaster' },
    'chatbot.kavim_2': { tr: 'Demirci Hasan', en: 'Smith Hasan' },
    'chatbot.kavim_3': { tr: 'Okçu Elif', en: 'Archer Elif' },
    'chatbot.kavim_4': { tr: 'Kaleci Yusuf', en: 'Keeper Yusuf' },
    'chatbot.kavim_5': { tr: 'Şifacı Ayşe', en: 'Healer Ayse' },
    'chatbot.kavim_6': { tr: 'Nöbetçi Kemal', en: 'Guard Kemal' },
    'chatbot.dunya_1': { tr: 'Gezgin Mert', en: 'Traveler Mert' },
    'chatbot.dunya_2': { tr: 'Tüccar Zeynep', en: 'Merchant Zeynep' },
    'chatbot.dunya_3': { tr: 'Avcı Burak', en: 'Hunter Burak' },
    'chatbot.dunya_4': { tr: 'Büyücü Selin', en: 'Mage Selin' },
    'chatbot.dunya_5': { tr: 'Savaşçı Ozan', en: 'Warrior Ozan' },
    'chatbot.dunya_6': { tr: 'Kaşif Deniz', en: 'Explorer Deniz' },
    'chatbot.dunya_7': { tr: 'Korsan Ali', en: 'Pirate Ali' },

    // ======================== CHAT BOT MESSAGES ========================
    'chatmsg.kavim_1': { tr: 'Bugün pazarda güzel malzeme var', en: 'Great materials at the market today' },
    'chatmsg.kavim_2': { tr: 'Kim T2 bölgesine gelecek?', en: 'Who is coming to T2 zone?' },
    'chatmsg.kavim_3': { tr: 'Boss spawn yakın dikkat!', en: 'Boss spawn incoming, be ready!' },
    'chatmsg.kavim_4': { tr: 'Benim alet kırıldı yine', en: 'My tool broke again' },
    'chatmsg.kavim_5': { tr: 'Yeni craft yaptım, CP artıyor', en: 'New craft done, CP is rising' },
    'chatmsg.kavim_6': { tr: 'Şehir savunması için hazır olun', en: 'Get ready for city defense' },
    'chatmsg.kavim_7': { tr: 'Birisi takas yapmak ister mi?', en: 'Anyone want to trade?' },
    'chatmsg.kavim_8': { tr: 'Dungeon partisi kuralım', en: 'Let\'s form a dungeon party' },
    'chatmsg.kavim_9': { tr: 'T3 çok tehlikeli tek gitmeyin', en: 'T3 is very dangerous, don\'t go alone' },
    'chatmsg.kavim_10': { tr: 'Bugün şanslıydım, kırmızı düştü!', en: 'Got lucky today, red item dropped!' },
    'chatmsg.kavim_11': { tr: 'Banka dolu artık ne yapacağım', en: 'Bank is full, what should I do' },
    'chatmsg.kavim_12': { tr: 'Alet yükseltmesi çok pahalı', en: 'Tool enhancement is too expensive' },
    'chatmsg.dunya_1': { tr: 'Herkese iyi oyunlar!', en: 'Good games everyone!' },
    'chatmsg.dunya_2': { tr: 'Kar şehrinde büyük savaş var', en: 'Big war in Ice City' },
    'chatmsg.dunya_3': { tr: 'Kim trade yapmak ister?', en: 'Who wants to trade?' },
    'chatmsg.dunya_4': { tr: 'Yeni başlayanlar T1 bölgesinden başlasın', en: 'Beginners should start in T1 zone' },
    'chatmsg.dunya_5': { tr: 'Boss 5 dakikaya spawn oluyor', en: 'Boss spawning in 5 minutes' },
    'chatmsg.dunya_6': { tr: 'Kadim taş savaşı başladı!', en: 'Ancient stone war has begun!' },
    'chatmsg.dunya_7': { tr: 'Orman şehri kazandı!', en: 'Forest city won!' },
    'chatmsg.dunya_8': { tr: 'Çöl şehri güçleniyor', en: 'Desert city is getting stronger' },
    'chatmsg.dunya_9': { tr: 'En iyi farm yeri neresi?', en: 'Best farm spot?' },
    'chatmsg.dunya_10': { tr: 'T3 merkez çok kalabalık', en: 'T3 center is too crowded' },
    'chatmsg.dunya_11': { tr: 'Premium almaya değer mi?', en: 'Is premium worth it?' },
    'chatmsg.dunya_12': { tr: 'Benim CP 500 oldu sonunda', en: 'My CP finally reached 500' },
    'chatmsg.dunya_13': { tr: 'İttifak kuruyoruz, katılın!', en: 'Forming an alliance, join us!' },
    'chatmsg.dunya_14': { tr: 'Pazarda ucuz mal var koşun', en: 'Cheap items at the market, hurry!' },

    // ======================== CHAT SYSTEM MESSAGES ========================
    'sysmsg.1': { tr: 'Kadim Taş Savaşı 2 saat sonra başlıyor!', en: 'Ancient Stone War starting in 2 hours!' },
    'sysmsg.2': { tr: 'Kar Şehri dungeon etkinliği aktif', en: 'Ice City dungeon event active' },
    'sysmsg.3': { tr: 'Haftalık ödüller dağıtıldı! Postanı kontrol et.', en: 'Weekly rewards distributed! Check your mail.' },
    'sysmsg.4': { tr: '2x EXP etkinliği başladı! (2 saat)', en: '2x EXP event started! (2 hours)' },
    'sysmsg.5': { tr: 'T3 Merkez bölgesinde özel boss belirdi!', en: 'Special boss appeared in T3 Center zone!' },

    // ======================== EVENTS BOT NAMES ========================
    'evtbot.kar_1': { tr: 'Buzul Han', en: 'Glacier Khan' },
    'evtbot.kar_2': { tr: 'Kış Kılıcı', en: 'Winter Blade' },
    'evtbot.kar_3': { tr: 'Bora Kağan', en: 'Storm Khagan' },
    'evtbot.kar_4': { tr: 'Ayaz Bey', en: 'Frost Lord' },
    'evtbot.kar_5': { tr: 'Tipi Savaşçı', en: 'Blizzard Warrior' },
    'evtbot.kar_6': { tr: 'Kar Kurdu', en: 'Snow Wolf' },
    'evtbot.kar_7': { tr: 'Fırtına Reis', en: 'Storm Chief' },
    'evtbot.kar_8': { tr: 'Don Pençe', en: 'Frost Claw' },
    'evtbot.kar_9': { tr: 'Soğuk Nefes', en: 'Cold Breath' },
    'evtbot.kar_10': { tr: 'Buz Okçu', en: 'Ice Archer' },
    'evtbot.orman_1': { tr: 'Yaprak Savaşçı', en: 'Leaf Warrior' },
    'evtbot.orman_2': { tr: 'Kök Titan', en: 'Root Titan' },
    'evtbot.orman_3': { tr: 'Yeşil Yılan', en: 'Green Snake' },
    'evtbot.orman_4': { tr: 'Orman Ruhu', en: 'Forest Spirit' },
    'evtbot.orman_5': { tr: 'Ağaç Dev', en: 'Tree Giant' },
    'evtbot.orman_6': { tr: 'Yosun Kılıç', en: 'Moss Blade' },
    'evtbot.orman_7': { tr: 'Geyik Süvari', en: 'Deer Rider' },
    'evtbot.orman_8': { tr: 'Dal Okçu', en: 'Branch Archer' },
    'evtbot.orman_9': { tr: 'Kurt Avcı', en: 'Wolf Hunter' },
    'evtbot.orman_10': { tr: 'Çiçek Kalkan', en: 'Flower Shield' },
    'evtbot.col_1': { tr: 'Kum Fırtınası', en: 'Sandstorm' },
    'evtbot.col_2': { tr: 'Çöl Kartalı', en: 'Desert Eagle' },
    'evtbot.col_3': { tr: 'Güneş Kılıcı', en: 'Sun Blade' },
    'evtbot.col_4': { tr: 'Kaktüs Reis', en: 'Cactus Chief' },
    'evtbot.col_5': { tr: 'Vaha Muhafızı', en: 'Oasis Guardian' },
    'evtbot.col_6': { tr: 'Akrep Savaşçı', en: 'Scorpion Warrior' },
    'evtbot.col_7': { tr: 'Sıcak Rüzgar', en: 'Hot Wind' },
    'evtbot.col_8': { tr: 'Mızrak Bey', en: 'Spear Lord' },
    'evtbot.col_9': { tr: 'Deve Süvari', en: 'Camel Rider' },
    'evtbot.col_10': { tr: 'Altın Kalkan', en: 'Golden Shield' },

    // ======================== MISSING UI STRINGS ========================
    'ui.inv_full': { tr: 'Envanter dolu', en: 'Inventory full' },
    'ui.node_depleted': { tr: 'Node tükendi!', en: 'Node depleted!' },
    'ui.tool_incompatible': { tr: 'T{ttier} alet T{ntier} node\'da çalışmaz!', en: 'T{ttier} tool cannot work on T{ntier} node!' },
    'ui.lang_tr': { tr: '🇹🇷 Türkçe seçildi', en: '🇹🇷 Turkish selected' },
    'ui.lang_en': { tr: '🇬🇧 English selected', en: '🇬🇧 English selected' },
    'ui.no_chest': { tr: '❌ Sandık yok', en: '❌ No chest' },
    'ui.insufficient_gold': { tr: '❌ Yetersiz altın', en: '❌ Insufficient gold' },

    // ======================== CHAR CREATE / CITY PICK ========================
    'char.city_hint': { tr: 'Seçtiğin şehir kavmini belirler. Kavim Savaşı\'nda kavmin için savaşırsın!', en: 'Your city determines your tribe. You fight for your tribe in Tribal War!' },
    'char.cold_region': { tr: 'Soğuk dağlık bölge', en: 'Cold mountainous region' },
    'char.kar_tribe': { tr: 'Kar Kavmi', en: 'Ice Tribe' },
    'char.green_region': { tr: 'Yeşil orman bölge', en: 'Green forest region' },
    'char.orman_tribe': { tr: 'Orman Kavmi', en: 'Forest Tribe' },
    'char.hot_region': { tr: 'Sıcak çöl bölge', en: 'Hot desert region' },
    'char.col_tribe': { tr: 'Çöl Kavmi', en: 'Desert Tribe' },
    'char.ore_bonus': { tr: '⛏ Cevher +%30', en: '⛏ Ore +30%' },
    'char.fish_bonus': { tr: '🐟 Balık +%20', en: '🐟 Fish +20%' },
    'char.wood_bonus': { tr: '🪵 Odun +%30', en: '🪵 Wood +30%' },
    'char.herb_bonus': { tr: '🌿 Bitki +%20', en: '🌿 Herb +20%' },
    'char.stone_bonus': { tr: '🪨 Taş +%30', en: '🪨 Stone +30%' },
    'char.hide_bonus': { tr: '🦴 Deri +%20', en: '🦴 Hide +20%' },

    // ======================== WORLD MAP ========================
    'world.back': { tr: '◂ GERİ', en: '◂ BACK' },
    'world.title': { tr: 'DÜNYA HARİTASI', en: 'WORLD MAP' },
    'world.sub': { tr: '3 şehir · 6 bölge · 1 merkez', en: '3 cities · 6 zones · 1 center' },
    'world.city_badge': { tr: 'ŞEHİR', en: 'CITY' },
    'world.capital': { tr: 'BAŞKENT', en: 'CAPITAL' },
    'world.t1_kar_name': { tr: 'T1 Kar', en: 'T1 Ice' },
    'world.t2_vadi': { tr: 'T2 Vadi', en: 'T2 Valley' },
    'world.t3_center': { tr: 'T3 Merkez', en: 'T3 Center' },
    'world.t2_bataklik': { tr: 'T2 Bataklık', en: 'T2 Swamp' },
    'world.t1_orman_name': { tr: 'T1 Orman', en: 'T1 Forest' },
    'world.t2_corak': { tr: 'T2 Çorak', en: 'T2 Barren' },
    'world.t1_col_name': { tr: 'T1 Çöl', en: 'T1 Desert' },
    'world.legend_city': { tr: 'Şehir', en: 'City' },
    'world.legend_blue': { tr: 'Mavi T2', en: 'Blue T2' },
    'world.legend_red': { tr: 'Kırmızı T3', en: 'Red T3' },
    'world.here': { tr: '✦ BURADASIN', en: '✦ HERE' },
    'world.center_badge': { tr: 'MERKEZ', en: 'CENTER' },
    'travel.journey': { tr: '🚶 Yolculuk', en: '🚶 Journey' },
    'travel.seconds': { tr: 'sn...', en: 'sec...' },

    // ======================== MENU ========================
    'menu.back': { tr: '◂ GERİ', en: '◂ BACK' },
    'menu.title': { tr: 'MENÜ', en: 'MENU' },
    'menu.sub': { tr: 'Tüm hizmetler · etkinlikler', en: 'All services · events' },
    'menu.daily_event': { tr: 'Günlük Etkinlik', en: 'Daily Event' },
    'menu.stone_speed': { tr: 'Taş toplama hızı', en: 'Stone gathering speed' },
    'menu.craft_power': { tr: 'Craft üretim gücü', en: 'Craft production power' },
    'menu.statistics': { tr: 'İstatistik', en: 'Statistics' },
    'menu.statusbar_title': { tr: 'Menü', en: 'Menu' },

    // ======================== MODALS ========================
    'modal.ranking_title': { tr: '🏆 Sıralama', en: '🏆 Ranking' },
    'modal.ranking_sub': { tr: 'CP\'ye göre oyuncu sıralaması', en: 'Player ranking by CP' },
    'modal.loading': { tr: 'Yükleniyor...', en: 'Loading...' },
    'modal.friends_title': { tr: '👥 Arkadaşlar', en: '👥 Friends' },
    'modal.friends_sub': { tr: 'Arkadaş listesi & istekler', en: 'Friends list & requests' },
    'modal.stone_title': { tr: '⚔️ Kadim Taş', en: '⚔️ Ancient Stone' },
    'modal.stone_sub': { tr: 'Taş Savaşı', en: 'Stone War' },

    // ======================== EVENT / PVP ========================
    'evt.tribal_war': { tr: '⚔️ Kavim Savaşı', en: '⚔️ Tribal War' },
    'evt.tribal_war_desc': { tr: 'Her saat başı kavimlerin çarpıştığı arena', en: 'Arena where tribes clash every hour' },
    'evt.tribal_war_info': { tr: 'Kavim savaşında diğer kavimlerin savaşçılarına saldır!', en: 'Attack other tribe warriors in tribal war!' },
    'evt.tribal_war_time': { tr: '10 dakika', en: '10 minutes' },
    'evt.tribal_war_win': { tr: 'içinde en çok kill alan kavim kazanır.', en: 'The tribe with the most kills wins.' },
    'evt.tribal_war_reward': { tr: 'Kavim Savaşı Sandığı', en: 'Tribal War Chest' },
    'evt.tribal_war_reward2': { tr: 'verilir!', en: 'is awarded!' },
    'evt.join_war': { tr: '⚔️ SAVAŞA KATIL', en: '⚔️ JOIN WAR' },
    'evt.time_remaining': { tr: 'Kalan süre:', en: 'Time remaining:' },
    'evt.enemy_warriors': { tr: 'Düşman Savaşçılar', en: 'Enemy Warriors' },
    'evt.tribe_kar': { tr: 'Kar', en: 'Ice' },
    'evt.tribe_orman': { tr: 'Orman', en: 'Forest' },
    'evt.tribe_col': { tr: 'Çöl', en: 'Desert' },

    // ======================== BAG MODAL ========================
    'bag.title': { tr: '📦 ÇANTA', en: '📦 BAG' },
    'bag.subtitle': { tr: 'Envanter · Kuşanım', en: 'Inventory · Equipment' },
    'bag.equip_section': { tr: 'Kuşanım', en: 'Equipment' },
    'bag.weight': { tr: 'Ağırlık', en: 'Weight' },
    'bag.slot': { tr: 'Slot', en: 'Slot' },
    'bag.tab_all': { tr: 'Tümü', en: 'All' },
    'bag.tab_equip': { tr: 'Ekipman', en: 'Equipment' },
    'bag.tab_raw': { tr: 'Hammadde', en: 'Raw Material' },
    'bag.tab_use': { tr: 'Tüketim', en: 'Consumable' },
    'bag.tab_misc': { tr: 'Diğer', en: 'Other' },
    'bag.sort': { tr: '⇅ Sırala', en: '⇅ Sort' },
    'bag.item_count_label': { tr: '{n} eşya', en: '{n} items' },
    'bag.touch_hint': { tr: 'Dokun · pencere açılır', en: 'Tap · opens window' },

    // ======================== BANK MODAL ========================
    'bank.title': { tr: '🏦 BANKA', en: '🏦 BANK' },
    'bank.subtitle': { tr: 'Güvenli Depolama', en: 'Secure Storage' },
    'bank.inv_label': { tr: '📦 Envanter', en: '📦 Inventory' },
    'bank.to_bank': { tr: '→ Bankaya At', en: '→ To Bank' },
    'bank.sort': { tr: '⇅ Sırala', en: '⇅ Sort' },
    'bank.label': { tr: '🏛️ Banka', en: '🏛️ Bank' },
    'bank.safe_badge': { tr: 'GÜVENLİ', en: 'SAFE' },
    'bank.to_inv': { tr: '← Envantere Al', en: '← To Inventory' },

    // ======================== MARKET MODAL ========================
    'market.title': { tr: '🏪 PAZARYERİ', en: '🏪 MARKETPLACE' },
    'market.subtitle': { tr: 'Trading House', en: 'Trading House' },

    // ======================== BANK TRANSFER ========================
    'xfer.quantity': { tr: 'Kaç adet aktarılsın?', en: 'How many to transfer?' },
    'xfer.cancel': { tr: 'İptal', en: 'Cancel' },
    'xfer.confirm': { tr: 'Onayla', en: 'Confirm' },

    // ======================== GATHERING MODAL ========================
    'gather.gather_btn': { tr: 'TOPLA', en: 'GATHER' },
    'gather.title': { tr: '⛏ Toplama', en: '⛏ Gathering' },
    'gather.subtitle': { tr: 'Node kaynak detayları', en: 'Node resource details' },
    'gather.material': { tr: 'Materyal', en: 'Material' },
    'gather.color': { tr: 'Renk', en: 'Color' },
    'gather.zone': { tr: 'Bölge', en: 'Zone' },
    'gather.active_bonus': { tr: 'Aktif Bonuslar', en: 'Active Bonuses' },
    'gather.speed': { tr: 'Hız (item/dk)', en: 'Speed (item/min)' },
    'gather.double_chance': { tr: '2× Şansı', en: '2× Chance' },
    'gather.inv_title': { tr: 'Envanter', en: 'Inventory' },
    'gather.tab_all': { tr: 'Tümü', en: 'All' },
    'gather.tab_raw': { tr: 'Malzeme', en: 'Materials' },
    'gather.tab_equip': { tr: 'Ekipman', en: 'Equipment' },
    'gather.tab_misc': { tr: 'Diğer', en: 'Other' },
    'gather.progress': { tr: 'Toplanıyor...', en: 'Gathering...' },

    // ======================== DUNGEON MODAL ========================
    'dg.title': { tr: '🏰 Dungeon', en: '🏰 Dungeon' },
    'dg.floor_select': { tr: 'Kat seçimi', en: 'Floor selection' },
    'dg.exit': { tr: 'Çıkış', en: 'Exit' },
    'dg.fighting': { tr: 'Savaşılıyor...', en: 'Fighting...' },
    'dg.inv_title': { tr: 'Envanter', en: 'Inventory' },
    'dg.tab_all': { tr: 'Tümü', en: 'All' },
    'dg.tab_equip': { tr: 'Ekipman', en: 'Equipment' },
    'dg.tab_raw': { tr: 'Malzeme', en: 'Materials' },
    'dg.tab_misc': { tr: 'Diğer', en: 'Other' },
    'dg.summary_title': { tr: '🏰 Dungeon Özeti', en: '🏰 Dungeon Summary' },
    'dg.summary_sub': { tr: 'Savaş Raporu', en: 'Battle Report' },
    'dg.ok': { tr: 'Tamam', en: 'OK' },

    // ======================== TRAVEL MODAL ========================
    'travel.region': { tr: 'Bölge', en: 'Region' },
    'travel.option': { tr: 'Seyahat seçeneği', en: 'Travel option' },
    'travel.go': { tr: '▶ Seyahat Et', en: '▶ Travel' },

    // ======================== MOUNT MODAL ========================
    'mount.title': { tr: '🐴 BINEK', en: '🐴 MOUNT' },
    'mount.subtitle': { tr: 'Mount Sistemi', en: 'Mount System' },

    // ======================== CHAT ========================
    'chat.world_label': { tr: 'Dünya', en: 'World' },
    'chat.tribe_label': { tr: 'Kavim', en: 'Tribe' },
    'chat.private_label': { tr: 'Özel', en: 'Private' },
    'chat.system_label': { tr: 'Sistem', en: 'System' },
    'chat.world_option': { tr: '🌍 Dünya', en: '🌍 World' },
    'chat.tribe_option': { tr: '🏰 Kavim', en: '🏰 Tribe' },
    'chat.private_option': { tr: '💬 Özel', en: '💬 Private' },
    'chat.placeholder': { tr: 'Mesaj yaz...', en: 'Type a message...' },

    // ======================== BIOMEMOBS ========================
    'mob.kar_1': { tr: 'Buz İskeleti', en: 'Ice Skeleton' },
    'mob.kar_1_boss': { tr: 'Donmuş Ejder', en: 'Frozen Dragon' },
    'mob.kar_2': { tr: 'Buz Kurdu', en: 'Ice Wolf' },
    'mob.kar_2_boss': { tr: 'Kar Alfası', en: 'Snow Alpha' },
    'mob.kar_3': { tr: 'Buz Golemi', en: 'Ice Golem' },
    'mob.kar_3_boss': { tr: 'Kristal Titan', en: 'Crystal Titan' },
    'mob.kar_4': { tr: 'Don Ejderi', en: 'Frost Dragon' },
    'mob.kar_4_boss': { tr: 'Buzul Lordu', en: 'Glacier Lord' },
    'mob.kar_5': { tr: 'Buz Lich', en: 'Ice Lich' },
    'mob.kar_5_boss': { tr: 'Kış Kralı', en: 'Winter King' },
    'mob.orman_1': { tr: 'Orman Goblini', en: 'Forest Goblin' },
    'mob.orman_1_boss': { tr: 'Goblin Şefi', en: 'Goblin Chief' },
    'mob.orman_2': { tr: 'Zehirli Yılan', en: 'Poison Snake' },
    'mob.orman_2_boss': { tr: 'Dev Basilisk', en: 'Giant Basilisk' },
    'mob.orman_3': { tr: 'Ağaç Canavarı', en: 'Tree Monster' },
    'mob.orman_3_boss': { tr: 'Kadim Treant', en: 'Ancient Treant' },
    'mob.orman_4': { tr: 'Orman Trolü', en: 'Forest Troll' },
    'mob.orman_4_boss': { tr: 'Trol Kralı', en: 'Troll King' },
    'mob.orman_5': { tr: 'Karanlık Druid', en: 'Dark Druid' },
    'mob.orman_5_boss': { tr: 'Orman Tanrısı', en: 'Forest God' },
    'mob.col_1': { tr: 'Kum Böceği', en: 'Sand Beetle' },
    'mob.col_1_boss': { tr: 'Dev Akrep', en: 'Giant Scorpion' },
    'mob.col_2': { tr: 'Çöl Akrebi', en: 'Desert Scorpion' },
    'mob.col_2_boss': { tr: 'Zehir Kralı', en: 'Poison King' },
    'mob.col_3': { tr: 'Mumya Savaşçı', en: 'Mummy Warrior' },
    'mob.col_3_boss': { tr: 'Firavun', en: 'Pharaoh' },
    'mob.col_4': { tr: 'Ateş Elementi', en: 'Fire Elemental' },
    'mob.col_4_boss': { tr: 'Ateş Akrep', en: 'Fire Scorpion' },
    'mob.col_5': { tr: 'Çöl İblisi', en: 'Desert Demon' },
    'mob.col_5_boss': { tr: 'Cehennem Lordu', en: 'Hell Lord' },
    'biome.kar_name': { tr: 'Buz', en: 'Ice' },
    'biome.orman_name': { tr: 'Orman', en: 'Forest' },
    'biome.col_name': { tr: 'Çöl', en: 'Desert' },
    'biome.kar_perk': { tr: 'Kar Ustası', en: 'Ice Master' },
    'biome.orman_perk': { tr: 'Orman Ustası', en: 'Forest Master' },
    'biome.col_perk': { tr: 'Çöl Ustası', en: 'Desert Master' },

    // ======================== EXTRA MISSING ========================
    'enh.charm': { tr: 'Tılsım', en: 'Charm' },
  };

  function t(key, replacements) {
    var entry = STRINGS[key];
    if (!entry) return key;
    var str = entry[current] || entry['tr'] || key;
    if (replacements) {
      for (var k in replacements) {
        str = str.replace('{' + k + '}', replacements[k]);
      }
    }
    return str;
  }

  function setLang(lang) {
    current = lang;
    localStorage.setItem('skyzone_lang', lang);
    translatePage();
  }

  function getLang() { return current; }

  // HTML elementlerini data-t attribute ile çevir
  function translatePage() {
    var els = document.querySelectorAll('[data-t]');
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      var key = el.dataset.t;
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = t(key);
      } else {
        el.textContent = t(key);
      }
    }
    // data-t-html: innerHTML çevirisi (HTML içeren metinler)
    var htmlEls = document.querySelectorAll('[data-t-html]');
    for (var j = 0; j < htmlEls.length; j++) {
      htmlEls[j].innerHTML = t(htmlEls[j].dataset.tHtml);
    }
  }

  return { t: t, setLang: setLang, getLang: getLang, translatePage: translatePage, STRINGS: STRINGS };
})();

// Global shortcut
var t = SKY.LANG.t;
